(import (scheme base) (scheme file) (scheme eval) (scheme write) (scheme read) (liii check)
        (only (goldfish) load-library! library-registry-ref lib-record-exports))
(check-set-mode! 'report-failed)
(include "../fixtures/semantic-audit.scm")
(define references
  (call-with-input-file "tests/r7rs/fixtures/standard-exports.scm" read))
(check (length references) => 16)
(define (difference a b)
  (let loop ((rest a) (out '()))
    (if (null? rest) (reverse out)
      (loop (cdr rest) (if (memq (car rest) b) out (cons (car rest) out))))))
(for-each
  (lambda (entry)
    (let* ((name (car entry)) (expected (cdr entry))
           (id (string->symbol (string-append "exports." (symbol->string (cadr name))))))
      (audit-check id
        (lambda ()
          (load-library! name)
          (let ((actual (lib-record-exports (library-registry-ref name))))
            (display ";;;EXPORTS ") (write name)
            (display " required=") (display (length expected))
            (display " actual=") (display (length actual))
            (display " missing=") (write (difference expected actual))
            (display " extra=") (write (difference actual expected)) (newline)
            (difference expected actual)))
        '())))
  references)
(check-report)
