(import (scheme base) (scheme complex) (scheme inexact) (scheme eval) (scheme write) (liii check))
(check-set-mode! 'report-failed)
(include "../fixtures/semantic-audit.scm")
(audit-check 'numeric.tower (lambda () (list (complex? 3) (real? 3) (rational? 3) (integer? 3)
                                           (integer? 3.0) (rational? 3.5) (real? 1+2i) (complex? 1+2i)))
  '(#t #t #t #t #t #t #f #t))
(audit-check 'numeric.special-types (lambda () (list (real? +inf.0) (rational? +inf.0) (integer? +inf.0)
                                                   (nan? +nan.0) (infinite? -inf.0) (finite? 1/3))) '(#t #f #f #t #t #t))
(audit-check 'numeric.bignum (lambda () (= (+ (expt 2 200) 1) (- (+ (expt 2 200) 2) 1))) #t)
(audit-check 'numeric.rational (lambda () (list (/ 6 -8) (+ 1/3 1/6) (* 2/3 3/4) (numerator -3/4) (denominator -3/4)))
  '(-3/4 1/2 1/2 -3 4))
(audit-check 'numeric.exactness (lambda () (list (exact? (+ 1 2)) (inexact? (+ 1 2.0))
                                               (inexact? (max 1 2.0)) (exact (inexact 1/2)))) '(#t #t #t 1/2))
(audit-check 'numeric.complex (lambda () (list (+ 1+2i 3-2i) (* 1+2i 1-2i) (real-part 1+2i) (imag-part 1+2i))) '(4 5 1 2))
(audit-check 'numeric.division (lambda () (list (call-with-values (lambda () (floor/ -13 4)) list)
                                              (call-with-values (lambda () (truncate/ -13 4)) list)
                                              (call-with-values (lambda () (floor/ 13 -4)) list))) '((-4 3) (-3 -1) (-4 -3)))
(audit-check 'numeric.rounding (lambda () (list (floor -4.3) (ceiling -4.3) (truncate -4.3) (round 2.5) (round 3.5)))
  '(-5.0 -4.0 -4.0 2.0 4.0))
(audit-check 'numeric.comparison-boundary (lambda () (list (> 9007199254740993 9007199254740992.0)
                                                         (= 9007199254740993 9007199254740992.0)
                                                         (< -9007199254740993 -9007199254740992.0))) '(#t #f #t))
(audit-check 'numeric.rationalize (lambda () (list (rationalize 3/10 1/10) (rationalize -3/10 1/10)
                                                 (rationalize 1/3 0))) '(1/3 -1/3 1/3))
(audit-check 'numeric.integer-sqrt (lambda () (call-with-values (lambda () (exact-integer-sqrt (+ (expt 2 200) 1))) list))
  (list (expt 2 100) 1))
(audit-check 'numeric.syntax (lambda () (list (string->number "#e#x10") (string->number "#i3/2")
                                            (string->number "1+2i") (string->number "#b1010") (string->number "not-a-number")))
  '(16 1.5 1+2i 10 #f))
(audit-check 'numeric.radix-roundtrip
  (lambda () (let ((n (+ (expt 2 200) 42)))
               (map (lambda (radix) (= n (string->number (number->string n radix) radix))) '(2 8 10 16)))) '(#t #t #t #t))
(audit-check 'numeric.exact-roundtrip (lambda () (map (lambda (n) (eqv? n (string->number (number->string n))))
                                                    '(1/3 -7/8 1+2i))) '(#t #t #t))
(audit-check 'numeric.inexact-roundtrip
  (lambda () (map (lambda (n) (eqv? n (string->number (number->string n))))
                 (append '(0.1 -1.25 1.0e100)
                         (list (make-rectangular 1 0.0)
                               (make-rectangular 1.0 -0.0)
                               (make-rectangular 1 2.0)))))
  '(#t #t #t #t #t #t))
(check-report)
