(import (scheme base) (scheme eval) (scheme read) (scheme write) (liii check))
(check-set-mode! 'report-failed)
(include "../fixtures/semantic-audit.scm")
(define (datum text) (read (open-input-string text)))
(audit-check 'reader.identifiers (lambda () (datum "(λ |two words| |a\\x3bb;b| + - ... ->x)"))
             '(λ |two words| |aλb| + - ... ->x))
(audit-check 'reader.comments (lambda () (datum "; first\n#| outer #| inner |# done |# #;(ignored) (kept)")) '(kept))
(audit-check 'reader.nested-datum-comment (lambda () (datum "#;#;(a) (b) (c)")) '(c))
(audit-check 'reader.case-directives
  (lambda () (let ((p (open-input-string "#!fold-case ABC |MiXeD| #!no-fold-case DEF")))
               (list (read p) (read p) (read p)))) '(abc |MiXeD| DEF))
(audit-check 'reader.characters
  (lambda () (map datum '("#\\alarm" "#\\backspace" "#\\delete" "#\\escape" "#\\null" "#\\space" "#\\tab" "#\\x3bb")))
  (map integer->char '(7 8 127 27 0 32 9 955)))
(audit-check 'reader.string-escapes (lambda () (datum "\"a\\x3bb;\\t\\n\\\"\\\\b\"")) "aλ\t\n\"\\b")
(audit-check 'reader.string-continuation (lambda () (datum "\"a\\  \n  b\"")) "ab")
(audit-check 'reader.abbreviations (lambda () (datum "('a `b ,c ,@d)"))
  '((quote a) (quasiquote b) (unquote c) (unquote-splicing d)))
(audit-check 'reader.collections (lambda () (datum "(#(1 λ) #u8(0 255) (a . b) #true #false)"))
  (list #(1 λ) (bytevector 0 255) '(a . b) #t #f))
(audit-check 'reader.shared (lambda () (let ((x (datum "(#0=(a b) #0#)"))) (eq? (car x) (cadr x)))) #t)
(audit-check 'reader.cycle (lambda () (let ((x (datum "#0=(a . #0#)"))) (eq? x (cdr x)))) #t)
(audit-check 'reader.label-scope
  (lambda () (let ((p (open-input-string "#0=(a) #0#")))
               (read p) (guard (e (else #t)) (read p) #f))) #t)
(audit-check 'reader.error-kind (lambda () (guard (e (else (read-error? e))) (datum "(a") #f)) #t)
(audit-check 'reader.eof (lambda () (eof-object? (datum " ;done\n"))) #t)
(audit-check 'reader.numbers (lambda () (datum "(#e#x10 #i3/2 1+2i #b1010)")) '(16 1.5 1+2i 10))
(check-report)
