(library (extensible-match helpers)
  (export match-ellipsis?)
  (import (rnrs (6)))

  (define (exact-integer? n)
    (and (integer? n) (exact? n)))

  (define (match-ellipsis? pat)
    (syntax-case pat ()
      (ell
       (and (identifier? #'ell)
            (free-identifier=? #'ell #'(... ...)))
       #t)
      ((ell n)
       (and (identifier? #'ell)
            (free-identifier=? #'ell #'(... ...))
            (exact-integer? (syntax->datum #'n)))
       #t)
      ((ell min #t)
       (and (identifier? #'ell)
            (free-identifier=? #'ell #'(... ...))
            (exact-integer? (syntax->datum #'min)))
       #t)
      ((ell min max)
       (and (identifier? #'ell)
            (free-identifier=? #'ell #'(... ...))
            (exact-integer? (syntax->datum #'min))
            (exact-integer? (syntax->datum #'max)))
       #t)
      ((ell . _)
       (and (identifier? #'ell)
            (free-identifier=? #'ell #'(... ...)))
       (syntax-violation 'match "incorrect use of ellipsis" pat))
      (_ #f))))
