;; kernel.scm (goldfish): re-expanded by the expander to produce kernel-combined.scm.

(define-library (goldfish)
  ;; Export surface is the entry-point + transformer API only.  Internal
  ;; helpers (expand-*/qq-*/scan-*/store-*/context-* plumbing, core form
  ;; handlers, codegen constants) stay visible inside the library body but
  ;; are not importable: every name removed here has zero code references
  ;; outside goldfish/expander/kernel (verified 2026-09-10).
  (export
    *base-library*
    base-library
    binding-unstop
    bound-identifier=?
    compile-file
    compile-program
    compile-program-syntax
    compile-program-into-syntax
    compile-toplevel
    context-empty
    context-resolve
    core-form-binding?
    core-form-handlers
    *current-expand-context*
    current-expand-context
    *current-intro-scope*
    current-intro-scope
    datum->syntax
    def-bind!
    env-lookup
    eval-transformer
    expand
    expand-body
    expand-box
    expand-expr
    expand-lib-define-bind
    expand-lib-define-syntax
    expand-library-body
    expand-library-finalize
    expand-set-box!
    expand-stx
    expand-unbox
    exp-library-define!
    exp-library-ref
    free-identifier=?
    generate-temporaries
    identifier?
    initial-context
    lexical-binding?
    local-binder
    local-expand
    local-expand-body
    lower
    make-exp-library
    make-module-form-binding
    make-primitive-binding
    make-syntax-introducer
    make-toplevel-binding
    make-transformer-binding
    module-form-binding?
    new-defs
    primitive-binding?
    primitive-variables
    resolve-identifier
    set
    set<=?
    set=?
    set-add
    set-base-library!
    set-current-expand-context!
    set-current-intro-scope!
    set-flip
    set-fold
    set-member?
    set-remove
    set-subtract
    set-union
    stx-ctx-add
    stx-ctx-at
    stx-ctx-empty
    stx-ctx-mark-intro
    stx-set-library
    stx-vector?
    syntax->datum
    syntax-e
    syntax-local-introduce
    syntax-local-value
    take-macro-records
    the-base-library
    toplevel-binding?
    transformer-binding?
    tstop-binding?
    wrap-expression
    ;; runtime substrate (substrate.scm)
    *eof-object*
    *fresh-counter*
    *module-registry*
    eof-object
    force
    lookup-module
    make-fresh-name
    make-lazy-promise
    make-module
    make-record-type
    module?
    module-define!
    module-exports
    module-name
    module-ref
    next-fresh
    next-record-rtd
    record-accessor
    record-field-index
    record-instance?
    record-modifier
    record-predicate
    record-type?
    record-type-fields
    record-type-name
    register-module
    syntax-error
    the-expander-library
    vector-for-each
    vector-map
    *
    -
    /
    <
    <=
    =
    >
    >=
    abs
    acos
    angle
    append
    apply
    asin
    assoc
    assq
    assv
    atan
    binary-port?
    boolean=?
    boolean?
    bytevector
    bytevector?
    bytevector-append
    bytevector-copy
    bytevector-copy!
    bytevector-length
    bytevector->u8-list
    bytevector-u8-ref
    bytevector-u8-set!
    caaaar
    caaadr
    caaar
    caadar
    caaddr
    caadr
    caar
    cadaar
    cadadr
    cadar
    caddar
    cadddr
    caddr
    cadr
    call/cc
    call-with-current-continuation
    call-with-input-file
    call-with-output-file
    call-with-port
    call-with-values
    car
    cdaaar
    cdaadr
    cdaar
    cdadar
    cdaddr
    cdadr
    cdar
    cddaar
    cddadr
    cddar
    cdddar
    cddddr
    cdddr
    cddr
    cdr
    ceiling
    char<=?
    char<?
    char=?
    char>=?
    char>?
    char?
    char-alphabetic?
    char-ci<=?
    char-ci<?
    char-ci=?
    char-ci>=?
    char-ci>?
    char-downcase
    char-foldcase
    char->integer
    char-lower-case?
    char-numeric?
    char-ready?
    char-upcase
    char-upper-case?
    char-whitespace?
    close-input-port
    close-output-port
    close-port
    command-line
    complex?
    cons
    cos
    current-error-port
    current-input-port
    current-jiffy
    current-output-port
    current-second
    delete-file
    denominator
    digit-value
    display
    dynamic-wind
    emergency-exit
    environment
    eof-object?
    eq?
    equal?
    eqv?
    error
    eval
    even?
    exact
    exact?
    exact->inexact
    exact-integer-sqrt
    exit
    exp
    expt
    file-exists?
    finite?
    floor
    floor/
    floor-quotient
    floor-remainder
    flush-output-port
    for-each
    gcd
    get-environment-variable
    get-environment-variables
    get-output-bytevector
    get-output-string
    imag-part
    inexact
    inexact?
    inexact->exact
    infinite?
    input-port?
    input-port-open?
    integer?
    integer->char
    interaction-environment
    jiffies-per-second
    lcm
    length
    list
    list?
    list-copy
    list-ref
    list-set!
    list->string
    list-tail
    list->vector
    log
    magnitude
    make-bytevector
    make-list
    make-polar
    make-promise
    make-rectangular
    make-string
    make-syntax
    make-vector
    map
    max
    member
    memq
    memv
    min
    modulo
    nan?
    negative?
    newline
    not
    null?
    number?
    number->string
    numerator
    odd?
    open-input-bytevector
    open-input-file
    open-input-string
    open-output-bytevector
    open-output-file
    open-output-string
    output-port?
    output-port-open?
    pair?
    peek-char
    peek-u8
    port?
    positive?
    procedure?
    promise?
    quotient
    rational?
    rationalize
    read
    read-bytevector
    read-bytevector!
    read-char
    read-line
    read-string
    read-u8
    real?
    real-part
    remainder
    reverse
    round
    set-car!
    set-cdr!
    sin
    sqrt
    string
    string<=?
    string<?
    string=?
    string>=?
    string>?
    string?
    string-append
    string-ci<=?
    string-ci<?
    string-ci=?
    string-ci>=?
    string-ci>?
    string-copy
    string-copy!
    string-downcase
    string-fill!
    string-foldcase
    string-for-each
    string-length
    string->list
    string-map
    string->number
    string-ref
    string-set!
    string->symbol
    string-upcase
    string->utf8
    string->vector
    substring
    symbol=?
    symbol?
    symbol->string
    syntax?
    syntax-context
    syntax-form
    syntax-library
    tan
    textual-port?
    truncate
    truncate/
    truncate-quotient
    truncate-remainder
    u8-list->bytevector
    utf8->string
    values
    vector
    vector?
    vector-append
    vector-copy
    vector-copy!
    vector-fill!
    vector-length
    vector->list
    vector-ref
    vector-set!
    vector->string
    with-input-from-file
    with-output-to-file
    write
    write-bytevector
    write-char
    write-shared
    write-simple
    write-string
    write-u8
    zero?
    )
  (begin
    (include "expander/kernel/substrate.scm")
    (include "expander/kernel/exp-library.scm")
    (include "expander/kernel/sets.scm")
    (include "expander/kernel/store.scm")
    (include "expander/kernel/syntax-objects.scm")
    (include "expander/kernel/context.scm")
    (include "expander/kernel/expand.scm")
    (include "expander/kernel/transformer.scm")
    (include "expander/kernel/intdef.scm")
    (include "expander/kernel/core-forms.scm")
    (include "expander/kernel/libbody.scm")
    (include "expander/kernel/primitives.scm")
    (include "expander/kernel/driver.scm")))
