;; kernel.scm (goldfish): re-expanded by expander to produce artifact; bootstrap-0 uses load-kernel.scm.

(define-library (goldfish)
  (export
    *base-library*
    base-library
    biggest-subset
    binding-unstop
    body-def-head
    body-output-source
    body-stop-list
    bound-identifier=?
    build-lambda-stx
    build-stop-frame
    check-eval-when-situations
    collect-macro-record!
    compile-file
    compile-program
    compile-program*
    compile-toplevel
    context-add-prune-scope
    context-add-use-scope
    context-alloc-box
    context-alloc-def-env
    context-alloc-name
    context-alloc-scope
    context-at-phase
    context-bind
    context-empty
    context-extend-env
    context-reset-use-scopes
    context-resolve
    context-return
    context-with-env
    context-with-intro-scope
    context-with-store
    context-with-use-scopes
    core-begin
    core-define
    core-define-syntax
    core-eval-when
    core-form-binding?
    core-form-handlers
    core-if
    core-lambda
    core-letrec
    core-letrec*
    core-letrec-syntax
    core-let-syntax
    core-quasiquote
    core-quote
    core-quote-syntax
    core-set!
    core-syntax
    ctx-local-expand
    ctx-local-expand-defs
    ctx-local-expand-defs*
    *current-expand-context*
    current-expand-context
    *current-intro-scope*
    current-intro-scope
    datum->stx-ctx
    datum->stx-ctx-source
    datum->syntax
    def-bind!
    defs-scope
    emit-toplevel-ref
    env-empty
    env-extend
    env-lookup
    env-map-values
    eval-transformer
    eval-when-expand!
    expand
    expand-application
    expand-atom
    expand-body
    expand-body-finalize
    expand-body-form
    expand-body-seq
    expand-box
    expand-expr
    expand-lambda-binding
    expand-lambda-bindings
    expand-letrec-allocate
    expand-letrec-form
    expand-letrec-inits
    expand-lib-define-bind
    expand-lib-define-syntax
    expand-library-body
    expand-library-finalize
    expand-list
    expand-macro
    expand-macro-once
    expand-pair
    expand-set-box!
    expand-stx
    expand-syntax-bindings
    expand-syntax-bindings/rec
    expand-unbox
    exp-library-define!
    exp-library-ref
    free-identifier=?
    generate-temporaries
    host-forms
    identifier?
    initial-context
    install-core-forms!
    install-primitives!
    lexical-binding?
    lib-output-source
    lib-resolve-head
    local-binder
    local-expand
    local-expand-body
    lower
    lower-head
    *macro-records*
    make-core-form-binding
    make-exp-library
    make-lexical-binding
    make-module-form-binding
    make-primitive-binding
    make-syntax-introducer
    make-syntax-rules-transformer
    make-toplevel-binding
    make-transformer-binding
    make-tstop-binding
    map-spine
    module-form-binding?
    new-defs
    parse-internal-define
    parse-lambda-params
    primitive-binding?
    primitive-variables
    qq-atom
    qq-expand
    qq-head
    qq-list
    qq-unquote-form?
    qq-vector
    require-identifier
    resolve-identifier
    scan-body-form
    scan-def-form
    scan-head-loop
    scan-lib-head
    self-evaluating?
    set
    set<=?
    set=?
    set-add
    set-base-library!
    set-current-expand-context!
    set-current-intro-scope!
    set-flip
    set-fold
    set-member?
    set-remove
    set-subtract
    set-union
    stopped-form?
    store-alloc
    store-alloc-box
    store-alloc-def-env
    store-alloc-name
    store-alloc-scope
    store-bind
    store-box-ref
    store-box-set
    store-def-env-ref
    store-def-env-set
    store-empty
    store-lookup
    store-resolve
    stx-add-scope
    stx-add-scope-unchecked
    stx-add-then-flip
    stx-apply-ctx
    stx-cadr
    stx-ctx-add
    stx-ctx-add-then-flip
    stx-ctx-add-unchecked
    stx-ctx-at
    stx-ctx-empty
    stx-ctx-flip
    stx-ctx-mark-intro
    stx-ctx-prune
    stx-ctx-set
    stx-flip-intro-off
    stx-flip-scope
    stx-maybe-flip
    stx-prune-scopes
    stx-set-library
    stx-vector?
    syntax-case-spec->procedure-form
    syntax->datum
    syntax-e
    syntax-local-introduce
    syntax-local-value
    syntax-scopes
    take-macro-records
    the-base-library
    toplevel-binding?
    transformer-binding?
    transformer-spec->procedure-form
    tstop-binding?
    void-expr
    wrap-expression
    ;; runtime substrate (substrate.scm)
    *eof-object*
    *fresh-counter*
    *module-registry*
    eof-object
    force
    lookup-module
    make-fresh-name
    make-lazy-promise
    make-module
    make-record-type
    module?
    module-define!
    module-exports
    module-name
    module-ref
    next-fresh
    next-record-rtd
    record-accessor
    record-field-index
    record-instance?
    record-modifier
    record-predicate
    record-type?
    record-type-fields
    record-type-name
    register-module
    syntax-error
    the-expander-library
    vector-for-each
    vector-map
    *
    -
    /
    <
    <=
    =
    >
    >=
    abs
    acos
    angle
    append
    apply
    asin
    assoc
    assq
    assv
    atan
    binary-port?
    boolean=?
    boolean?
    bytevector
    bytevector?
    bytevector-append
    bytevector-copy
    bytevector-copy!
    bytevector-length
    bytevector->u8-list
    bytevector-u8-ref
    bytevector-u8-set!
    caaaar
    caaadr
    caaar
    caadar
    caaddr
    caadr
    caar
    cadaar
    cadadr
    cadar
    caddar
    cadddr
    caddr
    cadr
    call/cc
    call-with-current-continuation
    call-with-input-file
    call-with-output-file
    call-with-port
    call-with-values
    car
    cdaaar
    cdaadr
    cdaar
    cdadar
    cdaddr
    cdadr
    cdar
    cddaar
    cddadr
    cddar
    cdddar
    cddddr
    cdddr
    cddr
    cdr
    ceiling
    char<=?
    char<?
    char=?
    char>=?
    char>?
    char?
    char-alphabetic?
    char-ci<=?
    char-ci<?
    char-ci=?
    char-ci>=?
    char-ci>?
    char-downcase
    char-foldcase
    char->integer
    char-lower-case?
    char-numeric?
    char-ready?
    char-upcase
    char-upper-case?
    char-whitespace?
    close-input-port
    close-output-port
    close-port
    command-line
    complex?
    cons
    cos
    current-error-port
    current-input-port
    current-jiffy
    current-output-port
    current-second
    delete-file
    denominator
    digit-value
    display
    dynamic-wind
    emergency-exit
    environment
    eof-object?
    eq?
    equal?
    eqv?
    error
    eval
    even?
    exact
    exact?
    exact->inexact
    exact-integer-sqrt
    exit
    exp
    expt
    file-exists?
    finite?
    floor
    floor/
    floor-quotient
    floor-remainder
    flush-output-port
    for-each
    gcd
    get-environment-variable
    get-environment-variables
    get-output-bytevector
    get-output-string
    imag-part
    inexact
    inexact?
    inexact->exact
    infinite?
    input-port?
    input-port-open?
    integer?
    integer->char
    interaction-environment
    jiffies-per-second
    lcm
    length
    list
    list?
    list-copy
    list-ref
    list-set!
    list->string
    list-tail
    list->vector
    log
    magnitude
    make-bytevector
    make-list
    make-polar
    make-promise
    make-rectangular
    make-string
    make-syntax
    make-vector
    map
    max
    member
    memq
    memv
    min
    modulo
    nan?
    negative?
    newline
    not
    null?
    number?
    number->string
    numerator
    odd?
    open-input-bytevector
    open-input-file
    open-input-string
    open-output-bytevector
    open-output-file
    open-output-string
    output-port?
    output-port-open?
    pair?
    peek-char
    peek-u8
    port?
    positive?
    procedure?
    promise?
    quotient
    rational?
    rationalize
    read
    read-bytevector
    read-bytevector!
    read-char
    read-line
    read-string
    read-u8
    real?
    real-part
    remainder
    reverse
    round
    set-car!
    set-cdr!
    set-current-intro-scope!
    sin
    sqrt
    string
    string<=?
    string<?
    string=?
    string>=?
    string>?
    string?
    string-append
    string-ci<=?
    string-ci<?
    string-ci=?
    string-ci>=?
    string-ci>?
    string-copy
    string-copy!
    string-downcase
    string-fill!
    string-foldcase
    string-for-each
    string-length
    string->list
    string-map
    string->number
    string-ref
    string-set!
    string->symbol
    string-upcase
    string->utf8
    string->vector
    substring
    symbol=?
    symbol?
    symbol->string
    syntax?
    syntax-context
    syntax-form
    syntax-library
    tan
    textual-port?
    truncate
    truncate/
    truncate-quotient
    truncate-remainder
    u8-list->bytevector
    utf8->string
    values
    vector
    vector?
    vector-append
    vector-copy
    vector-copy!
    vector-fill!
    vector-length
    vector->list
    vector-ref
    vector-set!
    vector->string
    with-input-from-file
    with-output-to-file
    write
    write-bytevector
    write-char
    write-shared
    write-simple
    write-string
    write-u8
    zero?
    )
  (begin
    (include "expander/kernel/substrate.scm")
    (include "expander/kernel/exp-library.scm")
    (include "expander/kernel/sets.scm")
    (include "expander/kernel/env.scm")
    (include "expander/kernel/store.scm")
    (include "expander/kernel/syntax-objects.scm")
    (include "expander/kernel/context.scm")
    (include "expander/kernel/expand.scm")
    (include "expander/kernel/transformer.scm")
    (include "expander/kernel/intdef.scm")
    (include "expander/kernel/core-forms.scm")
    (include "expander/kernel/libbody.scm")
    (include "expander/kernel/primitives.scm")
    (include "expander/kernel/driver.scm")))
