(import (goldfish))
(define declaration-original-load-path *load-path*)
(set! *load-path* (cons "tests/r7rs/fixtures" *load-path*))
(import (scheme base) (scheme eval) (liii check)
        (only (goldfish) compile-file module-ref the-expander-library)
        (r7rs-audit declarations-nested) (r7rs-audit 18446744073709551616))
(check-set-mode! 'report-failed)
(check total => 42)
(check mixed => 17)
(check |Escaped| => 19)
(check text => "MiXeD")
(check sequence => '(first second third))
(check wide-name => 18446744073709551616)
(check (let ()
         (include-ci "fixtures/r7rs-audit/declaration-parts/expression.scm")
         expr-local) => 42)
(check (cond-expand ((library (scheme base)) #t) (else #f)) => #t)
(check (cond-expand ((library (r7rs-audit availability-only)) #t) (else #f)) => #t)
(check (cond-expand ((library (r7rs-audit wrong-name)) #t) (else #f)) => #f)
(check (cond-expand ((library (r7rs-audit absent)) #t) (else #f)) => #f)
(check (cond-expand ((and) 'yes) (else 'no)) => 'yes)
(check (cond-expand ((or) 'yes) (else 'no)) => 'no)
(check (cond-expand ((and else) 1) (else 2)) => 2)
(check (cond-expand ((and (not (library (r7rs-audit absent)))
                         (or unknown (library (r7rs-audit 7)))) 'yes) (else 'no)) => 'yes)

(define (rejects? datum)
  (guard (exception (else #t))
    (eval datum (environment '(scheme base))) #f))
(check (rejects? '(define-library (bad -1) (import (scheme base)))) => #t)
(check (rejects? '(define-library (bad 1.0) (import (scheme base)))) => #t)
(check (rejects? '(define-library (bad "x") (import (scheme base)))) => #t)
(check (rejects? '(define-library () (import (scheme base)))) => #t)
(check (rejects? '(define-library (bad file) (include "missing-file.scm"))) => #t)
(check (rejects? '(define-library (bad filename) (include-ci 42))) => #t)
(check (rejects? '(define-library (bad empty) (include-library-declarations))) => #t)
(check (rejects? '(define-library (bad cycle)
                    (include-library-declarations
                      "tests/r7rs/fixtures/r7rs-audit/declaration-parts/cycle.scm"))) => #t)
(check (rejects? '(cond-expand ((not r7rs extra) 1) (else 2))) => #t)
(check (rejects? '(cond-expand ((library (bad -1)) 1) (else 2))) => #t)
(check (rejects? '(cond-expand (else 1) (r7rs 2))) => #t)
(check (rejects? '(define-library (bad conditional)
                    (cond-expand (else (export x)) (r7rs (export y))))) => #t)
(check (rejects? '(cond-expand ((unknown-operator r7rs) 1) (else 2))) => #t)
(check (let ()
         (include-ci "fixtures/r7rs-audit/declaration-parts/expression.scm")
         expr-local) => 42)
(set! *load-path* declaration-original-load-path)
(check-report)
