(import (scheme base) (scheme write) (srfi srfi-128) (srfi srfi-113))
(define C (make-eq-comparator))
(define s1 (set C 1 2))
(define s2 (set C 2 3))
(define both (set-union s1 s2))
(display "size: ")
(display (set-size both))
(newline)
(display "has-1-and-3: ")
(display (and (set-contains? both 1) (set-contains? both 3)))
(newline)
(define fact (lambda (n) (if (= n 0) 1 (* n (fact (- n 1))))))
(display "fact5: ")
(display (fact 5))
(newline)
(display "vals: ")
(display (call-with-values (lambda () (values 7 8)) list))
(newline)
