(import (scheme base) (scheme write) (m2a-libB) (m2a-libC))
(display "combine: ")
(display (b-combine 3 4))
(newline)
(display "describe: ")
(display (b-describe 7))
(newline)
(display "direct-C: ")
(display (c-add (c-mul 2 2) (c-mul 3 3)))
(newline)
