;;; m2a-sem-values.scm -- executable CORE-SEMANTICS: values/splice/if.
;;; Agree class only (engines must print byte-identical output).
;;; Intentional divergences live in diverge-* (see diff-gf0.sh).
(import (scheme base) (scheme write))
(display "splice-plus: ")
(display (+ (values 1 2) 3))
(newline)
(display "splice-closure: ")
(display ((lambda (a b c) (+ a b c)) 1 (values 2 3)))
(newline)
(display "cwv-multi: ")
(display (call-with-values (lambda () (values 1 2)) list))
(newline)
(display "cwv-zero: ")
(display (call-with-values (lambda () (values)) list))
(newline)
(display "cwv-single: ")
(display (call-with-values (lambda () 7) list))
(newline)
(display "if-no-else: ")
(display (if #f 1))
(newline)
(display "begin-empty: ")
(display (begin))
(newline)
(define sem-r 1)
(define sem-r 2)
(display "redefine: ")
(display sem-r)
(newline)
(display "letrec-star: ")
(display (letrec* ((a 1) (b (+ a 1))) b))
(newline)
(display "set-missing-key: ")
(display (catch #t (lambda () (set! sem-missing-xyz 1)) (lambda (k . r) k)))
(newline)
(display "apply-nonproc-key: ")
(display (catch #t (lambda () (apply 1 '(2))) (lambda (k . r) k)))
(newline)
