;;; m2a-sem-control.scm -- executable CORE-SEMANTICS: wind/callcc/tail.
;;; Agree class only. Wind order, invoke values, multi-shot, deep tail.
(import (scheme base) (scheme write))
(define sem-log '())
(define (sem-mark! x) (set! sem-log (cons x sem-log)))
(catch #t
  (lambda ()
    (dynamic-wind
      (lambda () (sem-mark! 'b1))
      (lambda ()
        (dynamic-wind
          (lambda () (sem-mark! 'b2))
          (lambda () (error 'sem-boom "x"))
          (lambda () (sem-mark! 'a2))))
      (lambda () (sem-mark! 'a1))))
  (lambda args (sem-mark! 'handled)))
(display "wind: ")
(display (reverse sem-log))
(newline)
(define sem-k1 #f)
(define sem-fired #f)
(dynamic-wind (lambda () #t)
  (lambda () (call/cc (lambda (k) (set! sem-k1 k) 'cap)))
  (lambda () (sem-mark! 'aw)))
(set! sem-log '())
(if (not sem-fired) (begin (set! sem-fired #t) (sem-k1 'go)))
(sem-mark! 'end)
(display "invoke: ")
(display (reverse sem-log))
(newline)
(define sem-n 0)
(define sem-k2 #f)
(call/cc (lambda (k) (set! sem-k2 k)))
(set! sem-n (+ sem-n 1))
(if (< sem-n 3) (sem-k2 'again))
(display "multishot: ")
(display sem-n)
(newline)
(define (sem-loop n acc)
  (if (= n 0) acc (sem-loop (- n 1) (+ acc 1))))
(display "tail100k: ")
(display (sem-loop 100000 0))
(newline)
