(import (scheme base) (scheme write) (srfi srfi-1))
(define (my-map f xs)
  (if (null? xs) '() (cons (f (car xs)) (my-map f (cdr xs)))))
(define (my-filter p xs)
  (cond ((null? xs) '())
        ((p (car xs)) (cons (car xs) (my-filter p (cdr xs))))
        (else (my-filter p (cdr xs)))))
(define (even?/odd? n)
  (letrec ((even? (lambda (k) (if (= k 0) #t (odd? (- k 1)))))
           (odd? (lambda (k) (if (= k 0) #f (even? (- k 1))))))
    (even? n)))
(display "mymap: ")
(display (my-map (lambda (x) (* x x)) '(1 2 3 4)))
(newline)
(display "s1map-eq: ")
(display (equal? (my-map (lambda (x) (+ x 1)) '(1 2 3))
                 (map (lambda (x) (+ x 1)) '(1 2 3))))
(newline)
(define (even?/odd?-as-pred x) (= (remainder x 2) 0))
(display "filter: ")
(display (my-filter even?/odd?-as-pred '(1 2 3 4 5 6)))
(newline)
(display "even100: ")
(display (even?/odd? 100))
(newline)
(display "compose: ")
(display (((lambda (f g) (lambda (x) (f (g x))))
           (lambda (x) (* x 2)) (lambda (x) (+ x 3))) 10))
(newline)
