(import (scheme base) (scheme write) (srfi srfi-9) (goldfish))
(define-record-type :point
  (make-point x y)
  point?
  (x point-x point-set-x!)
  (y point-y))
(define-record-type :rect
  (make-rect origin corner)
  rect?
  (origin rect-origin)
  (corner rect-corner))
(define (rect-area r)
  (* (- (point-x (rect-corner r)) (point-x (rect-origin r)))
     (- (point-y (rect-corner r)) (point-y (rect-origin r)))))
(define p (make-point 1 2))
(display "point?: ")
(display (point? p))
(newline)
(display "x: ")
(display (point-x p))
(newline)
(point-set-x! p 10)
(display "x-after-set: ")
(display (point-x p))
(newline)
(display "rect?: ")
(display (rect? (make-rect (make-point 0 0) (make-point 3 4))))
(newline)
(display "area: ")
(display (rect-area (make-rect (make-point 0 0) (make-point 3 4))))
(newline)
(display "point-not-rect: ")
(display (rect? p))
(newline)
