(import (scheme base) (scheme write) (srfi srfi-13) (srfi srfi-133) (srfi srfi-125) (srfi srfi-128))
(define (string-join-words ws)
  (if (null? ws) "" (string-append (car ws) " " (string-join-words (cdr ws)))))
(define v (vector 3 1 4 1 5 9 2 6))
(define (insertion-sort! vec)
  (define n (vector-length vec))
  (define (outer i)
    (if (< i n)
      (begin (inner i) (outer (+ i 1)))
      vec))
  (define (inner j)
    (if (and (> j 0) (< (vector-ref vec j) (vector-ref vec (- j 1))))
      (begin (vector-swap! vec j (- j 1)) (inner (- j 1)))
      vec))
  (outer 1))
(insertion-sort! v)
(display "sorted: ")
(display (vector->list v))
(newline)
(display "joined: ")
(display (string-join-words '("a" "bb" "ccc")))
(newline)
(define h (make-hash-table (make-eq-comparator)))
(hash-table-set! h 'alpha 1)
(hash-table-set! h 'beta 2)
(hash-table-set! h (+ 40 2) "computed-key")
(display "hash-alpha: ")
(display (hash-table-ref h 'alpha))
(newline)
(display "hash-size: ")
(display (hash-table-size h))
(newline)
(display "str-map: ")
(display (string-map (lambda (c) (if (char=? c #\a) #\A c)) "abracadabra"))
(newline)
(display "vec-fold: ")
(display (vector-fold (lambda (acc x) (+ acc x)) 0 #(10 20 30)))
(newline)
