(import (scheme base) (scheme write) (liii match))
(define (classify x)
  (match x
    (() 'empty)
    ((1 2 3) 'one-two-three)
    ((a b c) (list 'triple a b c))
    ((a . rest) (list 'pair a rest))
    (#(1 (? number? n)) (list 'vec-one n))
    ((or 'yes 'y) 'affirmative)
    ((and (? number? n) (? (lambda (k) (> k 100)) big)) (list 'big-number big))
    ((? string? s) (list 'string s))
    (else (list 'other x))))
(define (deep m)
  (match m
    (('add a b) (+ a b))
    (('mul a b) (* a b))
    (('neg ('add a b)) (- (+ a b)))
    (('pair ('pair a b) c) (list a b c))
    (('list . rest) rest)
    (else 'no-match)))
(display "c1: ") (display (classify '())) (newline)
(display "c2: ") (display (classify '(1 2 3))) (newline)
(display "c3: ") (display (classify '(9 8))) (newline)
(display "c4: ") (display (classify '(7 . 8))) (newline)
(display "c5: ") (display (classify #(1 42))) (newline)
(display "c6: ") (display (classify 'y)) (newline)
(display "c7: ") (display (classify 150)) (newline)
(display "c8: ") (display (classify "hi")) (newline)
(display "c9: ") (display (classify '(x))) (newline)
(display "d1: ") (display (deep '(add 3 4))) (newline)
(display "d2: ") (display (deep '(neg (add 1 2)))) (newline)
(display "d3: ") (display (deep '(pair (pair 1 2) 3))) (newline)
(display "d4: ") (display (deep '(list 1 2 3))) (newline)
(display "d5: ") (display (deep '(unknown))) (newline)
