;;; substrate.scm -- expander runtime substrate.
;;;
;;; Host-compatible value surface + runtime module substrate that the kernel
;;; (and the pre-expanded artifact) needs AT EVALUATION TIME.  These used to
;;; live in the seed (liii/boot.scm); folding them into the kernel library
;;; makes the artifact self-contained: the lowered defs define records,
;;; promises, the module substrate, and fresh-name generation, so the seed
;;; only provides file utilities, list utilities, and the loader.
;;;
;;; All data that reaches the expander comes from our own R7RS reader
;;; (read-forms), which emits (quote ...) with the plain quote symbol --
;;; never s7's internal #_quote object -- so no s7 reader workaround is
;;; needed here.

;;; ---------------------------------------------------------------------------
;;; Independent record implementation (cf. Guile ice-9/boot-9.scm {Records}).
;;;
;;; The host s7 define-record-type builds inlet-based records: a record is a
;;; let whose first pair is its type tag, so let->list / list traversal of a
;;; record leaks that tag as data (e.g. ((<type> . <type>) (field . ...))).
;;; The expander kernel needs records that cannot be mistaken for association
;;; lists, so records are implemented here as a type descriptor plus a
;;; fixed-layout vector, with type identity tested by eq? on the descriptor
;;; (cf. Guile struct/vtable).
;;;
;;; Layout:  descriptor = (vector 'record-type name fields)
;;;          instance   = (vector descriptor field0 field1 ...)

(define (make-record-type type-name fields)
  (vector 'record-type type-name fields))

(define (record-type? obj)
  (and (vector? obj)
       (positive? (vector-length obj))
       (eq? (vector-ref obj 0) 'record-type)))

(define (record-type-name rtd)
  (vector-ref rtd 1))

(define (record-type-fields rtd)
  (vector-ref rtd 2))

;;; record-instance? : any -> bool
;;; True for vector-layout record instances (first element is a type
;;; descriptor).  Code that must tell records apart from ordinary vectors
;;; (e.g. the expander's stx-vector?, which recurses into container
;;; vectors) uses this to exclude records.

(define (record-instance? obj)
  (and (vector? obj)
       (positive? (vector-length obj))
       (record-type? (vector-ref obj 0))))

(define (record-predicate rtd)
  (lambda (obj)
    (and (vector? obj)
         (positive? (vector-length obj))
         (eq? (vector-ref obj 0) rtd))))

(define (record-field-index rtd field)
  (let loop ((fs (record-type-fields rtd)) (i 1))
    (cond ((null? fs) (error "record: no such field" field))
          ((eq? (car fs) field) i)
          (else (loop (cdr fs) (+ i 1))))))

(define (record-accessor rtd field)
  (let ((idx (record-field-index rtd field)))
    (lambda (obj) (vector-ref obj idx))))

(define (record-modifier rtd field)
  (let ((idx (record-field-index rtd field)))
    (lambda (obj val) (vector-set! obj idx val))))

;;; ---------------------------------------------------------------------------
;;; Fresh READABLE symbols (counter-based, not s7's {gensym}-N:M): the
;;; expander artifact is written as Scheme source and must round-trip
;;; through the R7RS reader, so names generated by host macros and by
;;; make-fresh-name are ordinary symbols.

(define *fresh-counter* 0)

(define (next-fresh stem)
  (set! *fresh-counter* (+ *fresh-counter* 1))
  (string->symbol (string-append stem "~" (number->string *fresh-counter*))))

(define (next-record-rtd)
  (next-fresh "rtd"))

(define (vector-map f v . more)
  (unless (procedure? f)
    (error 'wrong-type-arg "vector-map: first argument must be a procedure" f))
  (let* ((vs (cons v more))
         (n (vector-length v))
         (result (make-vector n)))
    (let loop ((i 0))
      (unless (= i n)
        (vector-set! result i
                     (apply f (map (lambda (v) (vector-ref v i)) vs)))
        (loop (+ i 1))))
    result))

(define (vector-for-each f v . more)
  (unless (procedure? f)
    (error 'wrong-type-arg "vector-for-each: first argument must be a procedure" f))
  (let* ((vs (cons v more))
         (n (vector-length v)))
    (let loop ((i 0))
      (unless (= i n)
        (apply f (map (lambda (v) (vector-ref v i)) vs))
        (loop (+ i 1))))))

(define (make-fresh-name stem)
  (next-fresh (symbol->string stem)))

;;; ---------------------------------------------------------------------------
;;; Promises (r7rs-small).  The host's r7rs mode provides make-promise /
;;; force / promise?, but its make-promise is value-semantics, so the R7RS
;;; delay desugar (make-promise (lambda () expr)) would store the thunk as
;;; the value.  delay / delay-force therefore construct a lazy promise in the
;;; host's representation directly; the host's force evaluates it once and
;;; caches (and recursively forces a promise-valued result).

(define (make-lazy-promise thunk)
  (list (cons #f thunk) '+promise+))

;; The host does not provide force (or promise?) in this configuration, so
;; implement the R7RS semantics for the make-lazy-promise representation
;; above: evaluate once, cache, and recursively force a promise-valued
;; result.

(define (force promise)
  (if (and (pair? promise)
           (pair? (cdr promise))
           (eq? (cadr promise) '+promise+))
    (let ((box (car promise)))
      (if (car box)
        (cdr box)
        (let ((value ((cdr box))))
          (set-car! box #t)
          (if (and (pair? value)
                   (pair? (cdr value))
                   (eq? (cadr value) '+promise+))
            (let ((result (force value)))
              (set-cdr! box result)
              result)
            (begin
              (set-cdr! box value)
              value)))))
    promise))

;;; ---------------------------------------------------------------------------
;;; r7rs-small procedures the host does not provide.

;; The host has no eof-object procedure (only the eof-object? predicate),
;; so construct the EOF object in pure Scheme: reading past the end of an
;; empty string returns the single EOF object.  The binding is captured once
;; here so every call returns the same object.

(define *eof-object* (read (open-input-string "")))

(define (eof-object)
  *eof-object*)

(define (syntax-error msg . irritants)
  (apply error (cons (string-append "syntax error: " msg) irritants)))

;;; ---------------------------------------------------------------------------
;;; Runtime module substrate.
;;;
;;; A module is an s7 inlet holding its bindings plus '__name and
;;; '__exports metadata.  module-define! adds a binding and records it
;;; as exported.  the-expander-library (the expander's own API module)
;;; is module instance zero; user R7RS runtime modules use the same
;;; substrate.  module-ref accepts a module object or a registered module
;;; name (the form emitted by the expander for cross-library references).
;;; Note: s7 eval falls back to rootlet for names absent from an inlet, so
;;; evaluating transformer code in the-expander-library documents the
;;; expander API surface without sandboxing it.

(define *module-registry* '())

(define (make-module name)
  (inlet '__name name '__exports '()))

(define (module? obj)
  (and (let? obj) (assq '__name (let->list obj)) #t))

(define (module-name m)
  (let-ref m '__name))

(define (module-exports m)
  (let-ref m '__exports))

(define (module-define! m name value)
  (if (assq name (let->list m))
    (let-set! m name value)
    (varlet m name value))
  (unless (memq name (let-ref m '__exports))
    (let-set! m '__exports (cons name (let-ref m '__exports))))
  m)

(define (module-ref m name)
  (let ((m (if (module? m) m (lookup-module m))))
    (unless (memq name (let-ref m '__exports))
      (error "module-ref: not exported" name))
    (let-ref m name)))

;;; A cross-library value reference is lowered to (module-ref 'home 'name);
;;; set! on such a reference lowers to ((setter module-ref) 'home 'name v)
;;; (core-set!), so module-ref needs a setter that writes through to the
;;; module's inlet.  This makes top-level set! to a program-library binding
;;; (or any registered module) work from macro-generated code.
(set! (setter module-ref)
      (lambda (m name value)
        (let ((m (if (module? m) m (lookup-module m))))
          (let-set! m name value))))

(define (register-module m)
  (let ((name (module-name m)))
    (set! *module-registry*
      (cons (cons name m)
            (filter (lambda (e) (not (equal? (car e) name)))
                    *module-registry*))))
  m)

(define (lookup-module name)
  (let ((entry (assoc name *module-registry*)))
    (unless entry
      (error "lookup-module: unknown module" name))
    (cdr entry)))

(define the-expander-library
  (make-module '(goldfish)))
