;;
;; Copyright (C) 2026 The Goldfish Scheme Authors
;;
;; Licensed under the Apache License, Version 2.0 (the "License");
;; you may not use this file except in compliance with the License.
;; You may obtain a copy of the License at
;;
;; http://www.apache.org/licenses/LICENSE-2.0
;;
;; Unless required by applicable law or agreed to in writing, software
;; distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
;; WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
;; License for the specific language governing permissions and limitations
;; under the License.
;;

(define-library (scheme char)
  (export char-upcase
    char-downcase
    char-foldcase
    char-upper-case?
    char-lower-case?
    digit-value
    char-numeric?
    char-alphabetic?
    char-whitespace?
    char-ci=?
    char-ci<?
    char-ci>?
    char-ci<=?
    char-ci>=?
    string-ci=?
    string-ci<?
    string-ci>?
    string-ci<=?
    string-ci>=?
    string-upcase
    string-downcase
    string-foldcase
  ) ;export
  (begin
    (define (digit-value ch)
      (case ch
       ((#\0 #\x3007 #\x96F6 #\xC601) 0)
       ;; 0 〇 零 영
       ((#\1 #\x4E00 #\x58F1 #\x58F9 #\xC77C) 1)
       ;; 1 一 壱 壹 일
       ((#\2 #\x4E8C #\x5F10 #\x8D30 #\xC774) 2)
       ;; 2 二 弐 贰 이
       ((#\3 #\x4E09 #\x53C2 #\x53C1 #\xC0BC) 3)
       ;; 3 三 参 叁 삼
       ((#\4 #\x56DB #\x8086 #\xC0AC) 4)
       ;; 4 四 肆 사
       ((#\5 #\x4E94 #\x4F0D #\xC624) 5)
       ;; 5 五 伍 오
       ((#\6 #\x516D #\x9678 #\x9646 #\xC721) 6)
       ;; 6 六 陸 陆 육
       ((#\7 #\x4E03 #\x67D2 #\xCE60) 7)
       ;; 7 七 柒 칠
       ((#\8 #\x516B #\x634C #\xD314) 8)
       ;; 8 八 捌 팔
       ((#\9 #\x4E5D #\x7396 #\xAD6C) 9)
       ;; 9 九 玖 구
       (else #f)
      ) ;case
    ) ;define

    (define (char-upcase char)
      (unless (char? char)
        (error 'type-error "char-upcase: parameter must be character")
      ) ;unless
      (let ((cp (char->integer char)))
        (cond ((<= 97 cp 122) (integer->char (+ cp -32)))
              ((= cp 181) (integer->char (+ cp 743)))
              ((<= 224 cp 246) (integer->char (+ cp -32)))
              ((<= 248 cp 254) (integer->char (+ cp -32)))
              ((= cp 255) (integer->char (+ cp 121)))
              ((= cp 257) (integer->char (+ cp -1)))
              ((= cp 259) (integer->char (+ cp -1)))
              ((= cp 261) (integer->char (+ cp -1)))
              ((= cp 263) (integer->char (+ cp -1)))
              ((= cp 265) (integer->char (+ cp -1)))
              ((= cp 267) (integer->char (+ cp -1)))
              ((= cp 269) (integer->char (+ cp -1)))
              ((= cp 271) (integer->char (+ cp -1)))
              ((= cp 273) (integer->char (+ cp -1)))
              ((= cp 275) (integer->char (+ cp -1)))
              ((= cp 277) (integer->char (+ cp -1)))
              ((= cp 279) (integer->char (+ cp -1)))
              ((= cp 281) (integer->char (+ cp -1)))
              ((= cp 283) (integer->char (+ cp -1)))
              ((= cp 285) (integer->char (+ cp -1)))
              ((= cp 287) (integer->char (+ cp -1)))
              ((= cp 289) (integer->char (+ cp -1)))
              ((= cp 291) (integer->char (+ cp -1)))
              ((= cp 293) (integer->char (+ cp -1)))
              ((= cp 295) (integer->char (+ cp -1)))
              ((= cp 297) (integer->char (+ cp -1)))
              ((= cp 299) (integer->char (+ cp -1)))
              ((= cp 301) (integer->char (+ cp -1)))
              ((= cp 303) (integer->char (+ cp -1)))
              ((= cp 305) (integer->char (+ cp -232)))
              ((= cp 307) (integer->char (+ cp -1)))
              ((= cp 309) (integer->char (+ cp -1)))
              ((= cp 311) (integer->char (+ cp -1)))
              ((= cp 314) (integer->char (+ cp -1)))
              ((= cp 316) (integer->char (+ cp -1)))
              ((= cp 318) (integer->char (+ cp -1)))
              ((= cp 320) (integer->char (+ cp -1)))
              ((= cp 322) (integer->char (+ cp -1)))
              ((= cp 324) (integer->char (+ cp -1)))
              ((= cp 326) (integer->char (+ cp -1)))
              ((= cp 328) (integer->char (+ cp -1)))
              ((= cp 331) (integer->char (+ cp -1)))
              ((= cp 333) (integer->char (+ cp -1)))
              ((= cp 335) (integer->char (+ cp -1)))
              ((= cp 337) (integer->char (+ cp -1)))
              ((= cp 339) (integer->char (+ cp -1)))
              ((= cp 341) (integer->char (+ cp -1)))
              ((= cp 343) (integer->char (+ cp -1)))
              ((= cp 345) (integer->char (+ cp -1)))
              ((= cp 347) (integer->char (+ cp -1)))
              ((= cp 349) (integer->char (+ cp -1)))
              ((= cp 351) (integer->char (+ cp -1)))
              ((= cp 353) (integer->char (+ cp -1)))
              ((= cp 355) (integer->char (+ cp -1)))
              ((= cp 357) (integer->char (+ cp -1)))
              ((= cp 359) (integer->char (+ cp -1)))
              ((= cp 361) (integer->char (+ cp -1)))
              ((= cp 363) (integer->char (+ cp -1)))
              ((= cp 365) (integer->char (+ cp -1)))
              ((= cp 367) (integer->char (+ cp -1)))
              ((= cp 369) (integer->char (+ cp -1)))
              ((= cp 371) (integer->char (+ cp -1)))
              ((= cp 373) (integer->char (+ cp -1)))
              ((= cp 375) (integer->char (+ cp -1)))
              ((= cp 378) (integer->char (+ cp -1)))
              ((= cp 380) (integer->char (+ cp -1)))
              ((= cp 382) (integer->char (+ cp -1)))
              ((= cp 383) (integer->char (+ cp -300)))
              ((= cp 384) (integer->char (+ cp 195)))
              ((= cp 387) (integer->char (+ cp -1)))
              ((= cp 389) (integer->char (+ cp -1)))
              ((= cp 392) (integer->char (+ cp -1)))
              ((= cp 396) (integer->char (+ cp -1)))
              ((= cp 402) (integer->char (+ cp -1)))
              ((= cp 405) (integer->char (+ cp 97)))
              ((= cp 409) (integer->char (+ cp -1)))
              ((= cp 410) (integer->char (+ cp 163)))
              ((= cp 411) (integer->char (+ cp 42561)))
              ((= cp 414) (integer->char (+ cp 130)))
              ((= cp 417) (integer->char (+ cp -1)))
              ((= cp 419) (integer->char (+ cp -1)))
              ((= cp 421) (integer->char (+ cp -1)))
              ((= cp 424) (integer->char (+ cp -1)))
              ((= cp 429) (integer->char (+ cp -1)))
              ((= cp 432) (integer->char (+ cp -1)))
              ((= cp 436) (integer->char (+ cp -1)))
              ((= cp 438) (integer->char (+ cp -1)))
              ((= cp 441) (integer->char (+ cp -1)))
              ((= cp 445) (integer->char (+ cp -1)))
              ((= cp 447) (integer->char (+ cp 56)))
              ((= cp 453) (integer->char (+ cp -1)))
              ((= cp 454) (integer->char (+ cp -2)))
              ((= cp 456) (integer->char (+ cp -1)))
              ((= cp 457) (integer->char (+ cp -2)))
              ((= cp 459) (integer->char (+ cp -1)))
              ((= cp 460) (integer->char (+ cp -2)))
              ((= cp 462) (integer->char (+ cp -1)))
              ((= cp 464) (integer->char (+ cp -1)))
              ((= cp 466) (integer->char (+ cp -1)))
              ((= cp 468) (integer->char (+ cp -1)))
              ((= cp 470) (integer->char (+ cp -1)))
              ((= cp 472) (integer->char (+ cp -1)))
              ((= cp 474) (integer->char (+ cp -1)))
              ((= cp 476) (integer->char (+ cp -1)))
              ((= cp 477) (integer->char (+ cp -79)))
              ((= cp 479) (integer->char (+ cp -1)))
              ((= cp 481) (integer->char (+ cp -1)))
              ((= cp 483) (integer->char (+ cp -1)))
              ((= cp 485) (integer->char (+ cp -1)))
              ((= cp 487) (integer->char (+ cp -1)))
              ((= cp 489) (integer->char (+ cp -1)))
              ((= cp 491) (integer->char (+ cp -1)))
              ((= cp 493) (integer->char (+ cp -1)))
              ((= cp 495) (integer->char (+ cp -1)))
              ((= cp 498) (integer->char (+ cp -1)))
              ((= cp 499) (integer->char (+ cp -2)))
              ((= cp 501) (integer->char (+ cp -1)))
              ((= cp 505) (integer->char (+ cp -1)))
              ((= cp 507) (integer->char (+ cp -1)))
              ((= cp 509) (integer->char (+ cp -1)))
              ((= cp 511) (integer->char (+ cp -1)))
              ((= cp 513) (integer->char (+ cp -1)))
              ((= cp 515) (integer->char (+ cp -1)))
              ((= cp 517) (integer->char (+ cp -1)))
              ((= cp 519) (integer->char (+ cp -1)))
              ((= cp 521) (integer->char (+ cp -1)))
              ((= cp 523) (integer->char (+ cp -1)))
              ((= cp 525) (integer->char (+ cp -1)))
              ((= cp 527) (integer->char (+ cp -1)))
              ((= cp 529) (integer->char (+ cp -1)))
              ((= cp 531) (integer->char (+ cp -1)))
              ((= cp 533) (integer->char (+ cp -1)))
              ((= cp 535) (integer->char (+ cp -1)))
              ((= cp 537) (integer->char (+ cp -1)))
              ((= cp 539) (integer->char (+ cp -1)))
              ((= cp 541) (integer->char (+ cp -1)))
              ((= cp 543) (integer->char (+ cp -1)))
              ((= cp 547) (integer->char (+ cp -1)))
              ((= cp 549) (integer->char (+ cp -1)))
              ((= cp 551) (integer->char (+ cp -1)))
              ((= cp 553) (integer->char (+ cp -1)))
              ((= cp 555) (integer->char (+ cp -1)))
              ((= cp 557) (integer->char (+ cp -1)))
              ((= cp 559) (integer->char (+ cp -1)))
              ((= cp 561) (integer->char (+ cp -1)))
              ((= cp 563) (integer->char (+ cp -1)))
              ((= cp 572) (integer->char (+ cp -1)))
              ((<= 575 cp 576) (integer->char (+ cp 10815)))
              ((= cp 578) (integer->char (+ cp -1)))
              ((= cp 583) (integer->char (+ cp -1)))
              ((= cp 585) (integer->char (+ cp -1)))
              ((= cp 587) (integer->char (+ cp -1)))
              ((= cp 589) (integer->char (+ cp -1)))
              ((= cp 591) (integer->char (+ cp -1)))
              ((= cp 592) (integer->char (+ cp 10783)))
              ((= cp 593) (integer->char (+ cp 10780)))
              ((= cp 594) (integer->char (+ cp 10782)))
              ((= cp 595) (integer->char (+ cp -210)))
              ((= cp 596) (integer->char (+ cp -206)))
              ((<= 598 cp 599) (integer->char (+ cp -205)))
              ((= cp 601) (integer->char (+ cp -202)))
              ((= cp 603) (integer->char (+ cp -203)))
              ((= cp 604) (integer->char (+ cp 42319)))
              ((= cp 608) (integer->char (+ cp -205)))
              ((= cp 609) (integer->char (+ cp 42315)))
              ((= cp 611) (integer->char (+ cp -207)))
              ((= cp 612) (integer->char (+ cp 42343)))
              ((= cp 613) (integer->char (+ cp 42280)))
              ((= cp 614) (integer->char (+ cp 42308)))
              ((= cp 616) (integer->char (+ cp -209)))
              ((= cp 617) (integer->char (+ cp -211)))
              ((= cp 618) (integer->char (+ cp 42308)))
              ((= cp 619) (integer->char (+ cp 10743)))
              ((= cp 620) (integer->char (+ cp 42305)))
              ((= cp 623) (integer->char (+ cp -211)))
              ((= cp 625) (integer->char (+ cp 10749)))
              ((= cp 626) (integer->char (+ cp -213)))
              ((= cp 629) (integer->char (+ cp -214)))
              ((= cp 637) (integer->char (+ cp 10727)))
              ((= cp 640) (integer->char (+ cp -218)))
              ((= cp 642) (integer->char (+ cp 42307)))
              ((= cp 643) (integer->char (+ cp -218)))
              ((= cp 647) (integer->char (+ cp 42282)))
              ((= cp 648) (integer->char (+ cp -218)))
              ((= cp 649) (integer->char (+ cp -69)))
              ((<= 650 cp 651) (integer->char (+ cp -217)))
              ((= cp 652) (integer->char (+ cp -71)))
              ((= cp 658) (integer->char (+ cp -219)))
              ((= cp 669) (integer->char (+ cp 42261)))
              ((= cp 670) (integer->char (+ cp 42258)))
              ((= cp 837) (integer->char (+ cp 84)))
              ((= cp 881) (integer->char (+ cp -1)))
              ((= cp 883) (integer->char (+ cp -1)))
              ((= cp 887) (integer->char (+ cp -1)))
              ((<= 891 cp 893) (integer->char (+ cp 130)))
              ((= cp 940) (integer->char (+ cp -38)))
              ((<= 941 cp 943) (integer->char (+ cp -37)))
              ((<= 945 cp 961) (integer->char (+ cp -32)))
              ((= cp 962) (integer->char (+ cp -31)))
              ((<= 963 cp 971) (integer->char (+ cp -32)))
              ((= cp 972) (integer->char (+ cp -64)))
              ((<= 973 cp 974) (integer->char (+ cp -63)))
              ((= cp 976) (integer->char (+ cp -62)))
              ((= cp 977) (integer->char (+ cp -57)))
              ((= cp 981) (integer->char (+ cp -47)))
              ((= cp 982) (integer->char (+ cp -54)))
              ((= cp 983) (integer->char (+ cp -8)))
              ((= cp 985) (integer->char (+ cp -1)))
              ((= cp 987) (integer->char (+ cp -1)))
              ((= cp 989) (integer->char (+ cp -1)))
              ((= cp 991) (integer->char (+ cp -1)))
              ((= cp 993) (integer->char (+ cp -1)))
              ((= cp 995) (integer->char (+ cp -1)))
              ((= cp 997) (integer->char (+ cp -1)))
              ((= cp 999) (integer->char (+ cp -1)))
              ((= cp 1001) (integer->char (+ cp -1)))
              ((= cp 1003) (integer->char (+ cp -1)))
              ((= cp 1005) (integer->char (+ cp -1)))
              ((= cp 1007) (integer->char (+ cp -1)))
              ((= cp 1008) (integer->char (+ cp -86)))
              ((= cp 1009) (integer->char (+ cp -80)))
              ((= cp 1010) (integer->char (+ cp 7)))
              ((= cp 1011) (integer->char (+ cp -116)))
              ((= cp 1013) (integer->char (+ cp -96)))
              ((= cp 1016) (integer->char (+ cp -1)))
              ((= cp 1019) (integer->char (+ cp -1)))
              ((<= 1072 cp 1103) (integer->char (+ cp -32)))
              ((<= 1104 cp 1119) (integer->char (+ cp -80)))
              ((= cp 1121) (integer->char (+ cp -1)))
              ((= cp 1123) (integer->char (+ cp -1)))
              ((= cp 1125) (integer->char (+ cp -1)))
              ((= cp 1127) (integer->char (+ cp -1)))
              ((= cp 1129) (integer->char (+ cp -1)))
              ((= cp 1131) (integer->char (+ cp -1)))
              ((= cp 1133) (integer->char (+ cp -1)))
              ((= cp 1135) (integer->char (+ cp -1)))
              ((= cp 1137) (integer->char (+ cp -1)))
              ((= cp 1139) (integer->char (+ cp -1)))
              ((= cp 1141) (integer->char (+ cp -1)))
              ((= cp 1143) (integer->char (+ cp -1)))
              ((= cp 1145) (integer->char (+ cp -1)))
              ((= cp 1147) (integer->char (+ cp -1)))
              ((= cp 1149) (integer->char (+ cp -1)))
              ((= cp 1151) (integer->char (+ cp -1)))
              ((= cp 1153) (integer->char (+ cp -1)))
              ((= cp 1163) (integer->char (+ cp -1)))
              ((= cp 1165) (integer->char (+ cp -1)))
              ((= cp 1167) (integer->char (+ cp -1)))
              ((= cp 1169) (integer->char (+ cp -1)))
              ((= cp 1171) (integer->char (+ cp -1)))
              ((= cp 1173) (integer->char (+ cp -1)))
              ((= cp 1175) (integer->char (+ cp -1)))
              ((= cp 1177) (integer->char (+ cp -1)))
              ((= cp 1179) (integer->char (+ cp -1)))
              ((= cp 1181) (integer->char (+ cp -1)))
              ((= cp 1183) (integer->char (+ cp -1)))
              ((= cp 1185) (integer->char (+ cp -1)))
              ((= cp 1187) (integer->char (+ cp -1)))
              ((= cp 1189) (integer->char (+ cp -1)))
              ((= cp 1191) (integer->char (+ cp -1)))
              ((= cp 1193) (integer->char (+ cp -1)))
              ((= cp 1195) (integer->char (+ cp -1)))
              ((= cp 1197) (integer->char (+ cp -1)))
              ((= cp 1199) (integer->char (+ cp -1)))
              ((= cp 1201) (integer->char (+ cp -1)))
              ((= cp 1203) (integer->char (+ cp -1)))
              ((= cp 1205) (integer->char (+ cp -1)))
              ((= cp 1207) (integer->char (+ cp -1)))
              ((= cp 1209) (integer->char (+ cp -1)))
              ((= cp 1211) (integer->char (+ cp -1)))
              ((= cp 1213) (integer->char (+ cp -1)))
              ((= cp 1215) (integer->char (+ cp -1)))
              ((= cp 1218) (integer->char (+ cp -1)))
              ((= cp 1220) (integer->char (+ cp -1)))
              ((= cp 1222) (integer->char (+ cp -1)))
              ((= cp 1224) (integer->char (+ cp -1)))
              ((= cp 1226) (integer->char (+ cp -1)))
              ((= cp 1228) (integer->char (+ cp -1)))
              ((= cp 1230) (integer->char (+ cp -1)))
              ((= cp 1231) (integer->char (+ cp -15)))
              ((= cp 1233) (integer->char (+ cp -1)))
              ((= cp 1235) (integer->char (+ cp -1)))
              ((= cp 1237) (integer->char (+ cp -1)))
              ((= cp 1239) (integer->char (+ cp -1)))
              ((= cp 1241) (integer->char (+ cp -1)))
              ((= cp 1243) (integer->char (+ cp -1)))
              ((= cp 1245) (integer->char (+ cp -1)))
              ((= cp 1247) (integer->char (+ cp -1)))
              ((= cp 1249) (integer->char (+ cp -1)))
              ((= cp 1251) (integer->char (+ cp -1)))
              ((= cp 1253) (integer->char (+ cp -1)))
              ((= cp 1255) (integer->char (+ cp -1)))
              ((= cp 1257) (integer->char (+ cp -1)))
              ((= cp 1259) (integer->char (+ cp -1)))
              ((= cp 1261) (integer->char (+ cp -1)))
              ((= cp 1263) (integer->char (+ cp -1)))
              ((= cp 1265) (integer->char (+ cp -1)))
              ((= cp 1267) (integer->char (+ cp -1)))
              ((= cp 1269) (integer->char (+ cp -1)))
              ((= cp 1271) (integer->char (+ cp -1)))
              ((= cp 1273) (integer->char (+ cp -1)))
              ((= cp 1275) (integer->char (+ cp -1)))
              ((= cp 1277) (integer->char (+ cp -1)))
              ((= cp 1279) (integer->char (+ cp -1)))
              ((= cp 1281) (integer->char (+ cp -1)))
              ((= cp 1283) (integer->char (+ cp -1)))
              ((= cp 1285) (integer->char (+ cp -1)))
              ((= cp 1287) (integer->char (+ cp -1)))
              ((= cp 1289) (integer->char (+ cp -1)))
              ((= cp 1291) (integer->char (+ cp -1)))
              ((= cp 1293) (integer->char (+ cp -1)))
              ((= cp 1295) (integer->char (+ cp -1)))
              ((= cp 1297) (integer->char (+ cp -1)))
              ((= cp 1299) (integer->char (+ cp -1)))
              ((= cp 1301) (integer->char (+ cp -1)))
              ((= cp 1303) (integer->char (+ cp -1)))
              ((= cp 1305) (integer->char (+ cp -1)))
              ((= cp 1307) (integer->char (+ cp -1)))
              ((= cp 1309) (integer->char (+ cp -1)))
              ((= cp 1311) (integer->char (+ cp -1)))
              ((= cp 1313) (integer->char (+ cp -1)))
              ((= cp 1315) (integer->char (+ cp -1)))
              ((= cp 1317) (integer->char (+ cp -1)))
              ((= cp 1319) (integer->char (+ cp -1)))
              ((= cp 1321) (integer->char (+ cp -1)))
              ((= cp 1323) (integer->char (+ cp -1)))
              ((= cp 1325) (integer->char (+ cp -1)))
              ((= cp 1327) (integer->char (+ cp -1)))
              ((<= 1377 cp 1414) (integer->char (+ cp -48)))
              ((<= 4304 cp 4346) (integer->char (+ cp 3008)))
              ((<= 4349 cp 4351) (integer->char (+ cp 3008)))
              ((<= 5112 cp 5117) (integer->char (+ cp -8)))
              ((= cp 7296) (integer->char (+ cp -6254)))
              ((= cp 7297) (integer->char (+ cp -6253)))
              ((= cp 7298) (integer->char (+ cp -6244)))
              ((<= 7299 cp 7300) (integer->char (+ cp -6242)))
              ((= cp 7301) (integer->char (+ cp -6243)))
              ((= cp 7302) (integer->char (+ cp -6236)))
              ((= cp 7303) (integer->char (+ cp -6181)))
              ((= cp 7304) (integer->char (+ cp 35266)))
              ((= cp 7306) (integer->char (+ cp -1)))
              ((= cp 7545) (integer->char (+ cp 35332)))
              ((= cp 7549) (integer->char (+ cp 3814)))
              ((= cp 7566) (integer->char (+ cp 35384)))
              ((= cp 7681) (integer->char (+ cp -1)))
              ((= cp 7683) (integer->char (+ cp -1)))
              ((= cp 7685) (integer->char (+ cp -1)))
              ((= cp 7687) (integer->char (+ cp -1)))
              ((= cp 7689) (integer->char (+ cp -1)))
              ((= cp 7691) (integer->char (+ cp -1)))
              ((= cp 7693) (integer->char (+ cp -1)))
              ((= cp 7695) (integer->char (+ cp -1)))
              ((= cp 7697) (integer->char (+ cp -1)))
              ((= cp 7699) (integer->char (+ cp -1)))
              ((= cp 7701) (integer->char (+ cp -1)))
              ((= cp 7703) (integer->char (+ cp -1)))
              ((= cp 7705) (integer->char (+ cp -1)))
              ((= cp 7707) (integer->char (+ cp -1)))
              ((= cp 7709) (integer->char (+ cp -1)))
              ((= cp 7711) (integer->char (+ cp -1)))
              ((= cp 7713) (integer->char (+ cp -1)))
              ((= cp 7715) (integer->char (+ cp -1)))
              ((= cp 7717) (integer->char (+ cp -1)))
              ((= cp 7719) (integer->char (+ cp -1)))
              ((= cp 7721) (integer->char (+ cp -1)))
              ((= cp 7723) (integer->char (+ cp -1)))
              ((= cp 7725) (integer->char (+ cp -1)))
              ((= cp 7727) (integer->char (+ cp -1)))
              ((= cp 7729) (integer->char (+ cp -1)))
              ((= cp 7731) (integer->char (+ cp -1)))
              ((= cp 7733) (integer->char (+ cp -1)))
              ((= cp 7735) (integer->char (+ cp -1)))
              ((= cp 7737) (integer->char (+ cp -1)))
              ((= cp 7739) (integer->char (+ cp -1)))
              ((= cp 7741) (integer->char (+ cp -1)))
              ((= cp 7743) (integer->char (+ cp -1)))
              ((= cp 7745) (integer->char (+ cp -1)))
              ((= cp 7747) (integer->char (+ cp -1)))
              ((= cp 7749) (integer->char (+ cp -1)))
              ((= cp 7751) (integer->char (+ cp -1)))
              ((= cp 7753) (integer->char (+ cp -1)))
              ((= cp 7755) (integer->char (+ cp -1)))
              ((= cp 7757) (integer->char (+ cp -1)))
              ((= cp 7759) (integer->char (+ cp -1)))
              ((= cp 7761) (integer->char (+ cp -1)))
              ((= cp 7763) (integer->char (+ cp -1)))
              ((= cp 7765) (integer->char (+ cp -1)))
              ((= cp 7767) (integer->char (+ cp -1)))
              ((= cp 7769) (integer->char (+ cp -1)))
              ((= cp 7771) (integer->char (+ cp -1)))
              ((= cp 7773) (integer->char (+ cp -1)))
              ((= cp 7775) (integer->char (+ cp -1)))
              ((= cp 7777) (integer->char (+ cp -1)))
              ((= cp 7779) (integer->char (+ cp -1)))
              ((= cp 7781) (integer->char (+ cp -1)))
              ((= cp 7783) (integer->char (+ cp -1)))
              ((= cp 7785) (integer->char (+ cp -1)))
              ((= cp 7787) (integer->char (+ cp -1)))
              ((= cp 7789) (integer->char (+ cp -1)))
              ((= cp 7791) (integer->char (+ cp -1)))
              ((= cp 7793) (integer->char (+ cp -1)))
              ((= cp 7795) (integer->char (+ cp -1)))
              ((= cp 7797) (integer->char (+ cp -1)))
              ((= cp 7799) (integer->char (+ cp -1)))
              ((= cp 7801) (integer->char (+ cp -1)))
              ((= cp 7803) (integer->char (+ cp -1)))
              ((= cp 7805) (integer->char (+ cp -1)))
              ((= cp 7807) (integer->char (+ cp -1)))
              ((= cp 7809) (integer->char (+ cp -1)))
              ((= cp 7811) (integer->char (+ cp -1)))
              ((= cp 7813) (integer->char (+ cp -1)))
              ((= cp 7815) (integer->char (+ cp -1)))
              ((= cp 7817) (integer->char (+ cp -1)))
              ((= cp 7819) (integer->char (+ cp -1)))
              ((= cp 7821) (integer->char (+ cp -1)))
              ((= cp 7823) (integer->char (+ cp -1)))
              ((= cp 7825) (integer->char (+ cp -1)))
              ((= cp 7827) (integer->char (+ cp -1)))
              ((= cp 7829) (integer->char (+ cp -1)))
              ((= cp 7835) (integer->char (+ cp -59)))
              ((= cp 7841) (integer->char (+ cp -1)))
              ((= cp 7843) (integer->char (+ cp -1)))
              ((= cp 7845) (integer->char (+ cp -1)))
              ((= cp 7847) (integer->char (+ cp -1)))
              ((= cp 7849) (integer->char (+ cp -1)))
              ((= cp 7851) (integer->char (+ cp -1)))
              ((= cp 7853) (integer->char (+ cp -1)))
              ((= cp 7855) (integer->char (+ cp -1)))
              ((= cp 7857) (integer->char (+ cp -1)))
              ((= cp 7859) (integer->char (+ cp -1)))
              ((= cp 7861) (integer->char (+ cp -1)))
              ((= cp 7863) (integer->char (+ cp -1)))
              ((= cp 7865) (integer->char (+ cp -1)))
              ((= cp 7867) (integer->char (+ cp -1)))
              ((= cp 7869) (integer->char (+ cp -1)))
              ((= cp 7871) (integer->char (+ cp -1)))
              ((= cp 7873) (integer->char (+ cp -1)))
              ((= cp 7875) (integer->char (+ cp -1)))
              ((= cp 7877) (integer->char (+ cp -1)))
              ((= cp 7879) (integer->char (+ cp -1)))
              ((= cp 7881) (integer->char (+ cp -1)))
              ((= cp 7883) (integer->char (+ cp -1)))
              ((= cp 7885) (integer->char (+ cp -1)))
              ((= cp 7887) (integer->char (+ cp -1)))
              ((= cp 7889) (integer->char (+ cp -1)))
              ((= cp 7891) (integer->char (+ cp -1)))
              ((= cp 7893) (integer->char (+ cp -1)))
              ((= cp 7895) (integer->char (+ cp -1)))
              ((= cp 7897) (integer->char (+ cp -1)))
              ((= cp 7899) (integer->char (+ cp -1)))
              ((= cp 7901) (integer->char (+ cp -1)))
              ((= cp 7903) (integer->char (+ cp -1)))
              ((= cp 7905) (integer->char (+ cp -1)))
              ((= cp 7907) (integer->char (+ cp -1)))
              ((= cp 7909) (integer->char (+ cp -1)))
              ((= cp 7911) (integer->char (+ cp -1)))
              ((= cp 7913) (integer->char (+ cp -1)))
              ((= cp 7915) (integer->char (+ cp -1)))
              ((= cp 7917) (integer->char (+ cp -1)))
              ((= cp 7919) (integer->char (+ cp -1)))
              ((= cp 7921) (integer->char (+ cp -1)))
              ((= cp 7923) (integer->char (+ cp -1)))
              ((= cp 7925) (integer->char (+ cp -1)))
              ((= cp 7927) (integer->char (+ cp -1)))
              ((= cp 7929) (integer->char (+ cp -1)))
              ((= cp 7931) (integer->char (+ cp -1)))
              ((= cp 7933) (integer->char (+ cp -1)))
              ((= cp 7935) (integer->char (+ cp -1)))
              ((<= 7936 cp 7943) (integer->char (+ cp 8)))
              ((<= 7952 cp 7957) (integer->char (+ cp 8)))
              ((<= 7968 cp 7975) (integer->char (+ cp 8)))
              ((<= 7984 cp 7991) (integer->char (+ cp 8)))
              ((<= 8000 cp 8005) (integer->char (+ cp 8)))
              ((= cp 8017) (integer->char (+ cp 8)))
              ((= cp 8019) (integer->char (+ cp 8)))
              ((= cp 8021) (integer->char (+ cp 8)))
              ((= cp 8023) (integer->char (+ cp 8)))
              ((<= 8032 cp 8039) (integer->char (+ cp 8)))
              ((<= 8048 cp 8049) (integer->char (+ cp 74)))
              ((<= 8050 cp 8053) (integer->char (+ cp 86)))
              ((<= 8054 cp 8055) (integer->char (+ cp 100)))
              ((<= 8056 cp 8057) (integer->char (+ cp 128)))
              ((<= 8058 cp 8059) (integer->char (+ cp 112)))
              ((<= 8060 cp 8061) (integer->char (+ cp 126)))
              ((<= 8064 cp 8071) (integer->char (+ cp 8)))
              ((<= 8080 cp 8087) (integer->char (+ cp 8)))
              ((<= 8096 cp 8103) (integer->char (+ cp 8)))
              ((<= 8112 cp 8113) (integer->char (+ cp 8)))
              ((= cp 8115) (integer->char (+ cp 9)))
              ((= cp 8126) (integer->char (+ cp -7205)))
              ((= cp 8131) (integer->char (+ cp 9)))
              ((<= 8144 cp 8145) (integer->char (+ cp 8)))
              ((<= 8160 cp 8161) (integer->char (+ cp 8)))
              ((= cp 8165) (integer->char (+ cp 7)))
              ((= cp 8179) (integer->char (+ cp 9)))
              ((= cp 8526) (integer->char (+ cp -28)))
              ((<= 8560 cp 8575) (integer->char (+ cp -16)))
              ((= cp 8580) (integer->char (+ cp -1)))
              ((<= 9424 cp 9449) (integer->char (+ cp -26)))
              ((<= 11312 cp 11359) (integer->char (+ cp -48)))
              ((= cp 11361) (integer->char (+ cp -1)))
              ((= cp 11365) (integer->char (+ cp -10795)))
              ((= cp 11366) (integer->char (+ cp -10792)))
              ((= cp 11368) (integer->char (+ cp -1)))
              ((= cp 11370) (integer->char (+ cp -1)))
              ((= cp 11372) (integer->char (+ cp -1)))
              ((= cp 11379) (integer->char (+ cp -1)))
              ((= cp 11382) (integer->char (+ cp -1)))
              ((= cp 11393) (integer->char (+ cp -1)))
              ((= cp 11395) (integer->char (+ cp -1)))
              ((= cp 11397) (integer->char (+ cp -1)))
              ((= cp 11399) (integer->char (+ cp -1)))
              ((= cp 11401) (integer->char (+ cp -1)))
              ((= cp 11403) (integer->char (+ cp -1)))
              ((= cp 11405) (integer->char (+ cp -1)))
              ((= cp 11407) (integer->char (+ cp -1)))
              ((= cp 11409) (integer->char (+ cp -1)))
              ((= cp 11411) (integer->char (+ cp -1)))
              ((= cp 11413) (integer->char (+ cp -1)))
              ((= cp 11415) (integer->char (+ cp -1)))
              ((= cp 11417) (integer->char (+ cp -1)))
              ((= cp 11419) (integer->char (+ cp -1)))
              ((= cp 11421) (integer->char (+ cp -1)))
              ((= cp 11423) (integer->char (+ cp -1)))
              ((= cp 11425) (integer->char (+ cp -1)))
              ((= cp 11427) (integer->char (+ cp -1)))
              ((= cp 11429) (integer->char (+ cp -1)))
              ((= cp 11431) (integer->char (+ cp -1)))
              ((= cp 11433) (integer->char (+ cp -1)))
              ((= cp 11435) (integer->char (+ cp -1)))
              ((= cp 11437) (integer->char (+ cp -1)))
              ((= cp 11439) (integer->char (+ cp -1)))
              ((= cp 11441) (integer->char (+ cp -1)))
              ((= cp 11443) (integer->char (+ cp -1)))
              ((= cp 11445) (integer->char (+ cp -1)))
              ((= cp 11447) (integer->char (+ cp -1)))
              ((= cp 11449) (integer->char (+ cp -1)))
              ((= cp 11451) (integer->char (+ cp -1)))
              ((= cp 11453) (integer->char (+ cp -1)))
              ((= cp 11455) (integer->char (+ cp -1)))
              ((= cp 11457) (integer->char (+ cp -1)))
              ((= cp 11459) (integer->char (+ cp -1)))
              ((= cp 11461) (integer->char (+ cp -1)))
              ((= cp 11463) (integer->char (+ cp -1)))
              ((= cp 11465) (integer->char (+ cp -1)))
              ((= cp 11467) (integer->char (+ cp -1)))
              ((= cp 11469) (integer->char (+ cp -1)))
              ((= cp 11471) (integer->char (+ cp -1)))
              ((= cp 11473) (integer->char (+ cp -1)))
              ((= cp 11475) (integer->char (+ cp -1)))
              ((= cp 11477) (integer->char (+ cp -1)))
              ((= cp 11479) (integer->char (+ cp -1)))
              ((= cp 11481) (integer->char (+ cp -1)))
              ((= cp 11483) (integer->char (+ cp -1)))
              ((= cp 11485) (integer->char (+ cp -1)))
              ((= cp 11487) (integer->char (+ cp -1)))
              ((= cp 11489) (integer->char (+ cp -1)))
              ((= cp 11491) (integer->char (+ cp -1)))
              ((= cp 11500) (integer->char (+ cp -1)))
              ((= cp 11502) (integer->char (+ cp -1)))
              ((= cp 11507) (integer->char (+ cp -1)))
              ((<= 11520 cp 11557) (integer->char (+ cp -7264)))
              ((= cp 11559) (integer->char (+ cp -7264)))
              ((= cp 11565) (integer->char (+ cp -7264)))
              ((= cp 42561) (integer->char (+ cp -1)))
              ((= cp 42563) (integer->char (+ cp -1)))
              ((= cp 42565) (integer->char (+ cp -1)))
              ((= cp 42567) (integer->char (+ cp -1)))
              ((= cp 42569) (integer->char (+ cp -1)))
              ((= cp 42571) (integer->char (+ cp -1)))
              ((= cp 42573) (integer->char (+ cp -1)))
              ((= cp 42575) (integer->char (+ cp -1)))
              ((= cp 42577) (integer->char (+ cp -1)))
              ((= cp 42579) (integer->char (+ cp -1)))
              ((= cp 42581) (integer->char (+ cp -1)))
              ((= cp 42583) (integer->char (+ cp -1)))
              ((= cp 42585) (integer->char (+ cp -1)))
              ((= cp 42587) (integer->char (+ cp -1)))
              ((= cp 42589) (integer->char (+ cp -1)))
              ((= cp 42591) (integer->char (+ cp -1)))
              ((= cp 42593) (integer->char (+ cp -1)))
              ((= cp 42595) (integer->char (+ cp -1)))
              ((= cp 42597) (integer->char (+ cp -1)))
              ((= cp 42599) (integer->char (+ cp -1)))
              ((= cp 42601) (integer->char (+ cp -1)))
              ((= cp 42603) (integer->char (+ cp -1)))
              ((= cp 42605) (integer->char (+ cp -1)))
              ((= cp 42625) (integer->char (+ cp -1)))
              ((= cp 42627) (integer->char (+ cp -1)))
              ((= cp 42629) (integer->char (+ cp -1)))
              ((= cp 42631) (integer->char (+ cp -1)))
              ((= cp 42633) (integer->char (+ cp -1)))
              ((= cp 42635) (integer->char (+ cp -1)))
              ((= cp 42637) (integer->char (+ cp -1)))
              ((= cp 42639) (integer->char (+ cp -1)))
              ((= cp 42641) (integer->char (+ cp -1)))
              ((= cp 42643) (integer->char (+ cp -1)))
              ((= cp 42645) (integer->char (+ cp -1)))
              ((= cp 42647) (integer->char (+ cp -1)))
              ((= cp 42649) (integer->char (+ cp -1)))
              ((= cp 42651) (integer->char (+ cp -1)))
              ((= cp 42787) (integer->char (+ cp -1)))
              ((= cp 42789) (integer->char (+ cp -1)))
              ((= cp 42791) (integer->char (+ cp -1)))
              ((= cp 42793) (integer->char (+ cp -1)))
              ((= cp 42795) (integer->char (+ cp -1)))
              ((= cp 42797) (integer->char (+ cp -1)))
              ((= cp 42799) (integer->char (+ cp -1)))
              ((= cp 42803) (integer->char (+ cp -1)))
              ((= cp 42805) (integer->char (+ cp -1)))
              ((= cp 42807) (integer->char (+ cp -1)))
              ((= cp 42809) (integer->char (+ cp -1)))
              ((= cp 42811) (integer->char (+ cp -1)))
              ((= cp 42813) (integer->char (+ cp -1)))
              ((= cp 42815) (integer->char (+ cp -1)))
              ((= cp 42817) (integer->char (+ cp -1)))
              ((= cp 42819) (integer->char (+ cp -1)))
              ((= cp 42821) (integer->char (+ cp -1)))
              ((= cp 42823) (integer->char (+ cp -1)))
              ((= cp 42825) (integer->char (+ cp -1)))
              ((= cp 42827) (integer->char (+ cp -1)))
              ((= cp 42829) (integer->char (+ cp -1)))
              ((= cp 42831) (integer->char (+ cp -1)))
              ((= cp 42833) (integer->char (+ cp -1)))
              ((= cp 42835) (integer->char (+ cp -1)))
              ((= cp 42837) (integer->char (+ cp -1)))
              ((= cp 42839) (integer->char (+ cp -1)))
              ((= cp 42841) (integer->char (+ cp -1)))
              ((= cp 42843) (integer->char (+ cp -1)))
              ((= cp 42845) (integer->char (+ cp -1)))
              ((= cp 42847) (integer->char (+ cp -1)))
              ((= cp 42849) (integer->char (+ cp -1)))
              ((= cp 42851) (integer->char (+ cp -1)))
              ((= cp 42853) (integer->char (+ cp -1)))
              ((= cp 42855) (integer->char (+ cp -1)))
              ((= cp 42857) (integer->char (+ cp -1)))
              ((= cp 42859) (integer->char (+ cp -1)))
              ((= cp 42861) (integer->char (+ cp -1)))
              ((= cp 42863) (integer->char (+ cp -1)))
              ((= cp 42874) (integer->char (+ cp -1)))
              ((= cp 42876) (integer->char (+ cp -1)))
              ((= cp 42879) (integer->char (+ cp -1)))
              ((= cp 42881) (integer->char (+ cp -1)))
              ((= cp 42883) (integer->char (+ cp -1)))
              ((= cp 42885) (integer->char (+ cp -1)))
              ((= cp 42887) (integer->char (+ cp -1)))
              ((= cp 42892) (integer->char (+ cp -1)))
              ((= cp 42897) (integer->char (+ cp -1)))
              ((= cp 42899) (integer->char (+ cp -1)))
              ((= cp 42900) (integer->char (+ cp 48)))
              ((= cp 42903) (integer->char (+ cp -1)))
              ((= cp 42905) (integer->char (+ cp -1)))
              ((= cp 42907) (integer->char (+ cp -1)))
              ((= cp 42909) (integer->char (+ cp -1)))
              ((= cp 42911) (integer->char (+ cp -1)))
              ((= cp 42913) (integer->char (+ cp -1)))
              ((= cp 42915) (integer->char (+ cp -1)))
              ((= cp 42917) (integer->char (+ cp -1)))
              ((= cp 42919) (integer->char (+ cp -1)))
              ((= cp 42921) (integer->char (+ cp -1)))
              ((= cp 42933) (integer->char (+ cp -1)))
              ((= cp 42935) (integer->char (+ cp -1)))
              ((= cp 42937) (integer->char (+ cp -1)))
              ((= cp 42939) (integer->char (+ cp -1)))
              ((= cp 42941) (integer->char (+ cp -1)))
              ((= cp 42943) (integer->char (+ cp -1)))
              ((= cp 42945) (integer->char (+ cp -1)))
              ((= cp 42947) (integer->char (+ cp -1)))
              ((= cp 42952) (integer->char (+ cp -1)))
              ((= cp 42954) (integer->char (+ cp -1)))
              ((= cp 42957) (integer->char (+ cp -1)))
              ((= cp 42961) (integer->char (+ cp -1)))
              ((= cp 42967) (integer->char (+ cp -1)))
              ((= cp 42969) (integer->char (+ cp -1)))
              ((= cp 42971) (integer->char (+ cp -1)))
              ((= cp 42998) (integer->char (+ cp -1)))
              ((= cp 43859) (integer->char (+ cp -928)))
              ((<= 43888 cp 43967) (integer->char (+ cp -38864)))
              ((<= 65345 cp 65370) (integer->char (+ cp -32)))
              ((<= 66600 cp 66639) (integer->char (+ cp -40)))
              ((<= 66776 cp 66811) (integer->char (+ cp -40)))
              ((<= 66967 cp 66977) (integer->char (+ cp -39)))
              ((<= 66979 cp 66993) (integer->char (+ cp -39)))
              ((<= 66995 cp 67001) (integer->char (+ cp -39)))
              ((<= 67003 cp 67004) (integer->char (+ cp -39)))
              ((<= 68800 cp 68850) (integer->char (+ cp -64)))
              ((<= 68976 cp 68997) (integer->char (+ cp -32)))
              ((<= 71872 cp 71903) (integer->char (+ cp -32)))
              ((<= 93792 cp 93823) (integer->char (+ cp -32)))
              ((<= 125218 cp 125251) (integer->char (+ cp -34)))
              (else char)
        ) ;cond
      ) ;let
    ) ;define

    (define (char-downcase char)
      (unless (char? char)
        (error 'type-error "char-downcase: parameter must be character")
      ) ;unless
      (let ((cp (char->integer char)))
        (cond ((<= 65 cp 90) (integer->char (+ cp 32)))
              ((<= 192 cp 214) (integer->char (+ cp 32)))
              ((<= 216 cp 222) (integer->char (+ cp 32)))
              ((= cp 256) (integer->char (+ cp 1)))
              ((= cp 258) (integer->char (+ cp 1)))
              ((= cp 260) (integer->char (+ cp 1)))
              ((= cp 262) (integer->char (+ cp 1)))
              ((= cp 264) (integer->char (+ cp 1)))
              ((= cp 266) (integer->char (+ cp 1)))
              ((= cp 268) (integer->char (+ cp 1)))
              ((= cp 270) (integer->char (+ cp 1)))
              ((= cp 272) (integer->char (+ cp 1)))
              ((= cp 274) (integer->char (+ cp 1)))
              ((= cp 276) (integer->char (+ cp 1)))
              ((= cp 278) (integer->char (+ cp 1)))
              ((= cp 280) (integer->char (+ cp 1)))
              ((= cp 282) (integer->char (+ cp 1)))
              ((= cp 284) (integer->char (+ cp 1)))
              ((= cp 286) (integer->char (+ cp 1)))
              ((= cp 288) (integer->char (+ cp 1)))
              ((= cp 290) (integer->char (+ cp 1)))
              ((= cp 292) (integer->char (+ cp 1)))
              ((= cp 294) (integer->char (+ cp 1)))
              ((= cp 296) (integer->char (+ cp 1)))
              ((= cp 298) (integer->char (+ cp 1)))
              ((= cp 300) (integer->char (+ cp 1)))
              ((= cp 302) (integer->char (+ cp 1)))
              ((= cp 304) (integer->char (+ cp -199)))
              ((= cp 306) (integer->char (+ cp 1)))
              ((= cp 308) (integer->char (+ cp 1)))
              ((= cp 310) (integer->char (+ cp 1)))
              ((= cp 313) (integer->char (+ cp 1)))
              ((= cp 315) (integer->char (+ cp 1)))
              ((= cp 317) (integer->char (+ cp 1)))
              ((= cp 319) (integer->char (+ cp 1)))
              ((= cp 321) (integer->char (+ cp 1)))
              ((= cp 323) (integer->char (+ cp 1)))
              ((= cp 325) (integer->char (+ cp 1)))
              ((= cp 327) (integer->char (+ cp 1)))
              ((= cp 330) (integer->char (+ cp 1)))
              ((= cp 332) (integer->char (+ cp 1)))
              ((= cp 334) (integer->char (+ cp 1)))
              ((= cp 336) (integer->char (+ cp 1)))
              ((= cp 338) (integer->char (+ cp 1)))
              ((= cp 340) (integer->char (+ cp 1)))
              ((= cp 342) (integer->char (+ cp 1)))
              ((= cp 344) (integer->char (+ cp 1)))
              ((= cp 346) (integer->char (+ cp 1)))
              ((= cp 348) (integer->char (+ cp 1)))
              ((= cp 350) (integer->char (+ cp 1)))
              ((= cp 352) (integer->char (+ cp 1)))
              ((= cp 354) (integer->char (+ cp 1)))
              ((= cp 356) (integer->char (+ cp 1)))
              ((= cp 358) (integer->char (+ cp 1)))
              ((= cp 360) (integer->char (+ cp 1)))
              ((= cp 362) (integer->char (+ cp 1)))
              ((= cp 364) (integer->char (+ cp 1)))
              ((= cp 366) (integer->char (+ cp 1)))
              ((= cp 368) (integer->char (+ cp 1)))
              ((= cp 370) (integer->char (+ cp 1)))
              ((= cp 372) (integer->char (+ cp 1)))
              ((= cp 374) (integer->char (+ cp 1)))
              ((= cp 376) (integer->char (+ cp -121)))
              ((= cp 377) (integer->char (+ cp 1)))
              ((= cp 379) (integer->char (+ cp 1)))
              ((= cp 381) (integer->char (+ cp 1)))
              ((= cp 385) (integer->char (+ cp 210)))
              ((= cp 386) (integer->char (+ cp 1)))
              ((= cp 388) (integer->char (+ cp 1)))
              ((= cp 390) (integer->char (+ cp 206)))
              ((= cp 391) (integer->char (+ cp 1)))
              ((<= 393 cp 394) (integer->char (+ cp 205)))
              ((= cp 395) (integer->char (+ cp 1)))
              ((= cp 398) (integer->char (+ cp 79)))
              ((= cp 399) (integer->char (+ cp 202)))
              ((= cp 400) (integer->char (+ cp 203)))
              ((= cp 401) (integer->char (+ cp 1)))
              ((= cp 403) (integer->char (+ cp 205)))
              ((= cp 404) (integer->char (+ cp 207)))
              ((= cp 406) (integer->char (+ cp 211)))
              ((= cp 407) (integer->char (+ cp 209)))
              ((= cp 408) (integer->char (+ cp 1)))
              ((= cp 412) (integer->char (+ cp 211)))
              ((= cp 413) (integer->char (+ cp 213)))
              ((= cp 415) (integer->char (+ cp 214)))
              ((= cp 416) (integer->char (+ cp 1)))
              ((= cp 418) (integer->char (+ cp 1)))
              ((= cp 420) (integer->char (+ cp 1)))
              ((= cp 422) (integer->char (+ cp 218)))
              ((= cp 423) (integer->char (+ cp 1)))
              ((= cp 425) (integer->char (+ cp 218)))
              ((= cp 428) (integer->char (+ cp 1)))
              ((= cp 430) (integer->char (+ cp 218)))
              ((= cp 431) (integer->char (+ cp 1)))
              ((<= 433 cp 434) (integer->char (+ cp 217)))
              ((= cp 435) (integer->char (+ cp 1)))
              ((= cp 437) (integer->char (+ cp 1)))
              ((= cp 439) (integer->char (+ cp 219)))
              ((= cp 440) (integer->char (+ cp 1)))
              ((= cp 444) (integer->char (+ cp 1)))
              ((= cp 452) (integer->char (+ cp 2)))
              ((= cp 453) (integer->char (+ cp 1)))
              ((= cp 455) (integer->char (+ cp 2)))
              ((= cp 456) (integer->char (+ cp 1)))
              ((= cp 458) (integer->char (+ cp 2)))
              ((= cp 459) (integer->char (+ cp 1)))
              ((= cp 461) (integer->char (+ cp 1)))
              ((= cp 463) (integer->char (+ cp 1)))
              ((= cp 465) (integer->char (+ cp 1)))
              ((= cp 467) (integer->char (+ cp 1)))
              ((= cp 469) (integer->char (+ cp 1)))
              ((= cp 471) (integer->char (+ cp 1)))
              ((= cp 473) (integer->char (+ cp 1)))
              ((= cp 475) (integer->char (+ cp 1)))
              ((= cp 478) (integer->char (+ cp 1)))
              ((= cp 480) (integer->char (+ cp 1)))
              ((= cp 482) (integer->char (+ cp 1)))
              ((= cp 484) (integer->char (+ cp 1)))
              ((= cp 486) (integer->char (+ cp 1)))
              ((= cp 488) (integer->char (+ cp 1)))
              ((= cp 490) (integer->char (+ cp 1)))
              ((= cp 492) (integer->char (+ cp 1)))
              ((= cp 494) (integer->char (+ cp 1)))
              ((= cp 497) (integer->char (+ cp 2)))
              ((= cp 498) (integer->char (+ cp 1)))
              ((= cp 500) (integer->char (+ cp 1)))
              ((= cp 502) (integer->char (+ cp -97)))
              ((= cp 503) (integer->char (+ cp -56)))
              ((= cp 504) (integer->char (+ cp 1)))
              ((= cp 506) (integer->char (+ cp 1)))
              ((= cp 508) (integer->char (+ cp 1)))
              ((= cp 510) (integer->char (+ cp 1)))
              ((= cp 512) (integer->char (+ cp 1)))
              ((= cp 514) (integer->char (+ cp 1)))
              ((= cp 516) (integer->char (+ cp 1)))
              ((= cp 518) (integer->char (+ cp 1)))
              ((= cp 520) (integer->char (+ cp 1)))
              ((= cp 522) (integer->char (+ cp 1)))
              ((= cp 524) (integer->char (+ cp 1)))
              ((= cp 526) (integer->char (+ cp 1)))
              ((= cp 528) (integer->char (+ cp 1)))
              ((= cp 530) (integer->char (+ cp 1)))
              ((= cp 532) (integer->char (+ cp 1)))
              ((= cp 534) (integer->char (+ cp 1)))
              ((= cp 536) (integer->char (+ cp 1)))
              ((= cp 538) (integer->char (+ cp 1)))
              ((= cp 540) (integer->char (+ cp 1)))
              ((= cp 542) (integer->char (+ cp 1)))
              ((= cp 544) (integer->char (+ cp -130)))
              ((= cp 546) (integer->char (+ cp 1)))
              ((= cp 548) (integer->char (+ cp 1)))
              ((= cp 550) (integer->char (+ cp 1)))
              ((= cp 552) (integer->char (+ cp 1)))
              ((= cp 554) (integer->char (+ cp 1)))
              ((= cp 556) (integer->char (+ cp 1)))
              ((= cp 558) (integer->char (+ cp 1)))
              ((= cp 560) (integer->char (+ cp 1)))
              ((= cp 562) (integer->char (+ cp 1)))
              ((= cp 570) (integer->char (+ cp 10795)))
              ((= cp 571) (integer->char (+ cp 1)))
              ((= cp 573) (integer->char (+ cp -163)))
              ((= cp 574) (integer->char (+ cp 10792)))
              ((= cp 577) (integer->char (+ cp 1)))
              ((= cp 579) (integer->char (+ cp -195)))
              ((= cp 580) (integer->char (+ cp 69)))
              ((= cp 581) (integer->char (+ cp 71)))
              ((= cp 582) (integer->char (+ cp 1)))
              ((= cp 584) (integer->char (+ cp 1)))
              ((= cp 586) (integer->char (+ cp 1)))
              ((= cp 588) (integer->char (+ cp 1)))
              ((= cp 590) (integer->char (+ cp 1)))
              ((= cp 880) (integer->char (+ cp 1)))
              ((= cp 882) (integer->char (+ cp 1)))
              ((= cp 886) (integer->char (+ cp 1)))
              ((= cp 895) (integer->char (+ cp 116)))
              ((= cp 902) (integer->char (+ cp 38)))
              ((<= 904 cp 906) (integer->char (+ cp 37)))
              ((= cp 908) (integer->char (+ cp 64)))
              ((<= 910 cp 911) (integer->char (+ cp 63)))
              ((<= 913 cp 929) (integer->char (+ cp 32)))
              ((<= 931 cp 939) (integer->char (+ cp 32)))
              ((= cp 975) (integer->char (+ cp 8)))
              ((= cp 984) (integer->char (+ cp 1)))
              ((= cp 986) (integer->char (+ cp 1)))
              ((= cp 988) (integer->char (+ cp 1)))
              ((= cp 990) (integer->char (+ cp 1)))
              ((= cp 992) (integer->char (+ cp 1)))
              ((= cp 994) (integer->char (+ cp 1)))
              ((= cp 996) (integer->char (+ cp 1)))
              ((= cp 998) (integer->char (+ cp 1)))
              ((= cp 1000) (integer->char (+ cp 1)))
              ((= cp 1002) (integer->char (+ cp 1)))
              ((= cp 1004) (integer->char (+ cp 1)))
              ((= cp 1006) (integer->char (+ cp 1)))
              ((= cp 1012) (integer->char (+ cp -60)))
              ((= cp 1015) (integer->char (+ cp 1)))
              ((= cp 1017) (integer->char (+ cp -7)))
              ((= cp 1018) (integer->char (+ cp 1)))
              ((<= 1021 cp 1023) (integer->char (+ cp -130)))
              ((<= 1024 cp 1039) (integer->char (+ cp 80)))
              ((<= 1040 cp 1071) (integer->char (+ cp 32)))
              ((= cp 1120) (integer->char (+ cp 1)))
              ((= cp 1122) (integer->char (+ cp 1)))
              ((= cp 1124) (integer->char (+ cp 1)))
              ((= cp 1126) (integer->char (+ cp 1)))
              ((= cp 1128) (integer->char (+ cp 1)))
              ((= cp 1130) (integer->char (+ cp 1)))
              ((= cp 1132) (integer->char (+ cp 1)))
              ((= cp 1134) (integer->char (+ cp 1)))
              ((= cp 1136) (integer->char (+ cp 1)))
              ((= cp 1138) (integer->char (+ cp 1)))
              ((= cp 1140) (integer->char (+ cp 1)))
              ((= cp 1142) (integer->char (+ cp 1)))
              ((= cp 1144) (integer->char (+ cp 1)))
              ((= cp 1146) (integer->char (+ cp 1)))
              ((= cp 1148) (integer->char (+ cp 1)))
              ((= cp 1150) (integer->char (+ cp 1)))
              ((= cp 1152) (integer->char (+ cp 1)))
              ((= cp 1162) (integer->char (+ cp 1)))
              ((= cp 1164) (integer->char (+ cp 1)))
              ((= cp 1166) (integer->char (+ cp 1)))
              ((= cp 1168) (integer->char (+ cp 1)))
              ((= cp 1170) (integer->char (+ cp 1)))
              ((= cp 1172) (integer->char (+ cp 1)))
              ((= cp 1174) (integer->char (+ cp 1)))
              ((= cp 1176) (integer->char (+ cp 1)))
              ((= cp 1178) (integer->char (+ cp 1)))
              ((= cp 1180) (integer->char (+ cp 1)))
              ((= cp 1182) (integer->char (+ cp 1)))
              ((= cp 1184) (integer->char (+ cp 1)))
              ((= cp 1186) (integer->char (+ cp 1)))
              ((= cp 1188) (integer->char (+ cp 1)))
              ((= cp 1190) (integer->char (+ cp 1)))
              ((= cp 1192) (integer->char (+ cp 1)))
              ((= cp 1194) (integer->char (+ cp 1)))
              ((= cp 1196) (integer->char (+ cp 1)))
              ((= cp 1198) (integer->char (+ cp 1)))
              ((= cp 1200) (integer->char (+ cp 1)))
              ((= cp 1202) (integer->char (+ cp 1)))
              ((= cp 1204) (integer->char (+ cp 1)))
              ((= cp 1206) (integer->char (+ cp 1)))
              ((= cp 1208) (integer->char (+ cp 1)))
              ((= cp 1210) (integer->char (+ cp 1)))
              ((= cp 1212) (integer->char (+ cp 1)))
              ((= cp 1214) (integer->char (+ cp 1)))
              ((= cp 1216) (integer->char (+ cp 15)))
              ((= cp 1217) (integer->char (+ cp 1)))
              ((= cp 1219) (integer->char (+ cp 1)))
              ((= cp 1221) (integer->char (+ cp 1)))
              ((= cp 1223) (integer->char (+ cp 1)))
              ((= cp 1225) (integer->char (+ cp 1)))
              ((= cp 1227) (integer->char (+ cp 1)))
              ((= cp 1229) (integer->char (+ cp 1)))
              ((= cp 1232) (integer->char (+ cp 1)))
              ((= cp 1234) (integer->char (+ cp 1)))
              ((= cp 1236) (integer->char (+ cp 1)))
              ((= cp 1238) (integer->char (+ cp 1)))
              ((= cp 1240) (integer->char (+ cp 1)))
              ((= cp 1242) (integer->char (+ cp 1)))
              ((= cp 1244) (integer->char (+ cp 1)))
              ((= cp 1246) (integer->char (+ cp 1)))
              ((= cp 1248) (integer->char (+ cp 1)))
              ((= cp 1250) (integer->char (+ cp 1)))
              ((= cp 1252) (integer->char (+ cp 1)))
              ((= cp 1254) (integer->char (+ cp 1)))
              ((= cp 1256) (integer->char (+ cp 1)))
              ((= cp 1258) (integer->char (+ cp 1)))
              ((= cp 1260) (integer->char (+ cp 1)))
              ((= cp 1262) (integer->char (+ cp 1)))
              ((= cp 1264) (integer->char (+ cp 1)))
              ((= cp 1266) (integer->char (+ cp 1)))
              ((= cp 1268) (integer->char (+ cp 1)))
              ((= cp 1270) (integer->char (+ cp 1)))
              ((= cp 1272) (integer->char (+ cp 1)))
              ((= cp 1274) (integer->char (+ cp 1)))
              ((= cp 1276) (integer->char (+ cp 1)))
              ((= cp 1278) (integer->char (+ cp 1)))
              ((= cp 1280) (integer->char (+ cp 1)))
              ((= cp 1282) (integer->char (+ cp 1)))
              ((= cp 1284) (integer->char (+ cp 1)))
              ((= cp 1286) (integer->char (+ cp 1)))
              ((= cp 1288) (integer->char (+ cp 1)))
              ((= cp 1290) (integer->char (+ cp 1)))
              ((= cp 1292) (integer->char (+ cp 1)))
              ((= cp 1294) (integer->char (+ cp 1)))
              ((= cp 1296) (integer->char (+ cp 1)))
              ((= cp 1298) (integer->char (+ cp 1)))
              ((= cp 1300) (integer->char (+ cp 1)))
              ((= cp 1302) (integer->char (+ cp 1)))
              ((= cp 1304) (integer->char (+ cp 1)))
              ((= cp 1306) (integer->char (+ cp 1)))
              ((= cp 1308) (integer->char (+ cp 1)))
              ((= cp 1310) (integer->char (+ cp 1)))
              ((= cp 1312) (integer->char (+ cp 1)))
              ((= cp 1314) (integer->char (+ cp 1)))
              ((= cp 1316) (integer->char (+ cp 1)))
              ((= cp 1318) (integer->char (+ cp 1)))
              ((= cp 1320) (integer->char (+ cp 1)))
              ((= cp 1322) (integer->char (+ cp 1)))
              ((= cp 1324) (integer->char (+ cp 1)))
              ((= cp 1326) (integer->char (+ cp 1)))
              ((<= 1329 cp 1366) (integer->char (+ cp 48)))
              ((<= 4256 cp 4293) (integer->char (+ cp 7264)))
              ((= cp 4295) (integer->char (+ cp 7264)))
              ((= cp 4301) (integer->char (+ cp 7264)))
              ((<= 5024 cp 5103) (integer->char (+ cp 38864)))
              ((<= 5104 cp 5109) (integer->char (+ cp 8)))
              ((= cp 7305) (integer->char (+ cp 1)))
              ((<= 7312 cp 7354) (integer->char (+ cp -3008)))
              ((<= 7357 cp 7359) (integer->char (+ cp -3008)))
              ((= cp 7680) (integer->char (+ cp 1)))
              ((= cp 7682) (integer->char (+ cp 1)))
              ((= cp 7684) (integer->char (+ cp 1)))
              ((= cp 7686) (integer->char (+ cp 1)))
              ((= cp 7688) (integer->char (+ cp 1)))
              ((= cp 7690) (integer->char (+ cp 1)))
              ((= cp 7692) (integer->char (+ cp 1)))
              ((= cp 7694) (integer->char (+ cp 1)))
              ((= cp 7696) (integer->char (+ cp 1)))
              ((= cp 7698) (integer->char (+ cp 1)))
              ((= cp 7700) (integer->char (+ cp 1)))
              ((= cp 7702) (integer->char (+ cp 1)))
              ((= cp 7704) (integer->char (+ cp 1)))
              ((= cp 7706) (integer->char (+ cp 1)))
              ((= cp 7708) (integer->char (+ cp 1)))
              ((= cp 7710) (integer->char (+ cp 1)))
              ((= cp 7712) (integer->char (+ cp 1)))
              ((= cp 7714) (integer->char (+ cp 1)))
              ((= cp 7716) (integer->char (+ cp 1)))
              ((= cp 7718) (integer->char (+ cp 1)))
              ((= cp 7720) (integer->char (+ cp 1)))
              ((= cp 7722) (integer->char (+ cp 1)))
              ((= cp 7724) (integer->char (+ cp 1)))
              ((= cp 7726) (integer->char (+ cp 1)))
              ((= cp 7728) (integer->char (+ cp 1)))
              ((= cp 7730) (integer->char (+ cp 1)))
              ((= cp 7732) (integer->char (+ cp 1)))
              ((= cp 7734) (integer->char (+ cp 1)))
              ((= cp 7736) (integer->char (+ cp 1)))
              ((= cp 7738) (integer->char (+ cp 1)))
              ((= cp 7740) (integer->char (+ cp 1)))
              ((= cp 7742) (integer->char (+ cp 1)))
              ((= cp 7744) (integer->char (+ cp 1)))
              ((= cp 7746) (integer->char (+ cp 1)))
              ((= cp 7748) (integer->char (+ cp 1)))
              ((= cp 7750) (integer->char (+ cp 1)))
              ((= cp 7752) (integer->char (+ cp 1)))
              ((= cp 7754) (integer->char (+ cp 1)))
              ((= cp 7756) (integer->char (+ cp 1)))
              ((= cp 7758) (integer->char (+ cp 1)))
              ((= cp 7760) (integer->char (+ cp 1)))
              ((= cp 7762) (integer->char (+ cp 1)))
              ((= cp 7764) (integer->char (+ cp 1)))
              ((= cp 7766) (integer->char (+ cp 1)))
              ((= cp 7768) (integer->char (+ cp 1)))
              ((= cp 7770) (integer->char (+ cp 1)))
              ((= cp 7772) (integer->char (+ cp 1)))
              ((= cp 7774) (integer->char (+ cp 1)))
              ((= cp 7776) (integer->char (+ cp 1)))
              ((= cp 7778) (integer->char (+ cp 1)))
              ((= cp 7780) (integer->char (+ cp 1)))
              ((= cp 7782) (integer->char (+ cp 1)))
              ((= cp 7784) (integer->char (+ cp 1)))
              ((= cp 7786) (integer->char (+ cp 1)))
              ((= cp 7788) (integer->char (+ cp 1)))
              ((= cp 7790) (integer->char (+ cp 1)))
              ((= cp 7792) (integer->char (+ cp 1)))
              ((= cp 7794) (integer->char (+ cp 1)))
              ((= cp 7796) (integer->char (+ cp 1)))
              ((= cp 7798) (integer->char (+ cp 1)))
              ((= cp 7800) (integer->char (+ cp 1)))
              ((= cp 7802) (integer->char (+ cp 1)))
              ((= cp 7804) (integer->char (+ cp 1)))
              ((= cp 7806) (integer->char (+ cp 1)))
              ((= cp 7808) (integer->char (+ cp 1)))
              ((= cp 7810) (integer->char (+ cp 1)))
              ((= cp 7812) (integer->char (+ cp 1)))
              ((= cp 7814) (integer->char (+ cp 1)))
              ((= cp 7816) (integer->char (+ cp 1)))
              ((= cp 7818) (integer->char (+ cp 1)))
              ((= cp 7820) (integer->char (+ cp 1)))
              ((= cp 7822) (integer->char (+ cp 1)))
              ((= cp 7824) (integer->char (+ cp 1)))
              ((= cp 7826) (integer->char (+ cp 1)))
              ((= cp 7828) (integer->char (+ cp 1)))
              ((= cp 7838) (integer->char (+ cp -7615)))
              ((= cp 7840) (integer->char (+ cp 1)))
              ((= cp 7842) (integer->char (+ cp 1)))
              ((= cp 7844) (integer->char (+ cp 1)))
              ((= cp 7846) (integer->char (+ cp 1)))
              ((= cp 7848) (integer->char (+ cp 1)))
              ((= cp 7850) (integer->char (+ cp 1)))
              ((= cp 7852) (integer->char (+ cp 1)))
              ((= cp 7854) (integer->char (+ cp 1)))
              ((= cp 7856) (integer->char (+ cp 1)))
              ((= cp 7858) (integer->char (+ cp 1)))
              ((= cp 7860) (integer->char (+ cp 1)))
              ((= cp 7862) (integer->char (+ cp 1)))
              ((= cp 7864) (integer->char (+ cp 1)))
              ((= cp 7866) (integer->char (+ cp 1)))
              ((= cp 7868) (integer->char (+ cp 1)))
              ((= cp 7870) (integer->char (+ cp 1)))
              ((= cp 7872) (integer->char (+ cp 1)))
              ((= cp 7874) (integer->char (+ cp 1)))
              ((= cp 7876) (integer->char (+ cp 1)))
              ((= cp 7878) (integer->char (+ cp 1)))
              ((= cp 7880) (integer->char (+ cp 1)))
              ((= cp 7882) (integer->char (+ cp 1)))
              ((= cp 7884) (integer->char (+ cp 1)))
              ((= cp 7886) (integer->char (+ cp 1)))
              ((= cp 7888) (integer->char (+ cp 1)))
              ((= cp 7890) (integer->char (+ cp 1)))
              ((= cp 7892) (integer->char (+ cp 1)))
              ((= cp 7894) (integer->char (+ cp 1)))
              ((= cp 7896) (integer->char (+ cp 1)))
              ((= cp 7898) (integer->char (+ cp 1)))
              ((= cp 7900) (integer->char (+ cp 1)))
              ((= cp 7902) (integer->char (+ cp 1)))
              ((= cp 7904) (integer->char (+ cp 1)))
              ((= cp 7906) (integer->char (+ cp 1)))
              ((= cp 7908) (integer->char (+ cp 1)))
              ((= cp 7910) (integer->char (+ cp 1)))
              ((= cp 7912) (integer->char (+ cp 1)))
              ((= cp 7914) (integer->char (+ cp 1)))
              ((= cp 7916) (integer->char (+ cp 1)))
              ((= cp 7918) (integer->char (+ cp 1)))
              ((= cp 7920) (integer->char (+ cp 1)))
              ((= cp 7922) (integer->char (+ cp 1)))
              ((= cp 7924) (integer->char (+ cp 1)))
              ((= cp 7926) (integer->char (+ cp 1)))
              ((= cp 7928) (integer->char (+ cp 1)))
              ((= cp 7930) (integer->char (+ cp 1)))
              ((= cp 7932) (integer->char (+ cp 1)))
              ((= cp 7934) (integer->char (+ cp 1)))
              ((<= 7944 cp 7951) (integer->char (+ cp -8)))
              ((<= 7960 cp 7965) (integer->char (+ cp -8)))
              ((<= 7976 cp 7983) (integer->char (+ cp -8)))
              ((<= 7992 cp 7999) (integer->char (+ cp -8)))
              ((<= 8008 cp 8013) (integer->char (+ cp -8)))
              ((= cp 8025) (integer->char (+ cp -8)))
              ((= cp 8027) (integer->char (+ cp -8)))
              ((= cp 8029) (integer->char (+ cp -8)))
              ((= cp 8031) (integer->char (+ cp -8)))
              ((<= 8040 cp 8047) (integer->char (+ cp -8)))
              ((<= 8072 cp 8079) (integer->char (+ cp -8)))
              ((<= 8088 cp 8095) (integer->char (+ cp -8)))
              ((<= 8104 cp 8111) (integer->char (+ cp -8)))
              ((<= 8120 cp 8121) (integer->char (+ cp -8)))
              ((<= 8122 cp 8123) (integer->char (+ cp -74)))
              ((= cp 8124) (integer->char (+ cp -9)))
              ((<= 8136 cp 8139) (integer->char (+ cp -86)))
              ((= cp 8140) (integer->char (+ cp -9)))
              ((<= 8152 cp 8153) (integer->char (+ cp -8)))
              ((<= 8154 cp 8155) (integer->char (+ cp -100)))
              ((<= 8168 cp 8169) (integer->char (+ cp -8)))
              ((<= 8170 cp 8171) (integer->char (+ cp -112)))
              ((= cp 8172) (integer->char (+ cp -7)))
              ((<= 8184 cp 8185) (integer->char (+ cp -128)))
              ((<= 8186 cp 8187) (integer->char (+ cp -126)))
              ((= cp 8188) (integer->char (+ cp -9)))
              ((= cp 8486) (integer->char (+ cp -7517)))
              ((= cp 8490) (integer->char (+ cp -8383)))
              ((= cp 8491) (integer->char (+ cp -8262)))
              ((= cp 8498) (integer->char (+ cp 28)))
              ((<= 8544 cp 8559) (integer->char (+ cp 16)))
              ((= cp 8579) (integer->char (+ cp 1)))
              ((<= 9398 cp 9423) (integer->char (+ cp 26)))
              ((<= 11264 cp 11311) (integer->char (+ cp 48)))
              ((= cp 11360) (integer->char (+ cp 1)))
              ((= cp 11362) (integer->char (+ cp -10743)))
              ((= cp 11363) (integer->char (+ cp -3814)))
              ((= cp 11364) (integer->char (+ cp -10727)))
              ((= cp 11367) (integer->char (+ cp 1)))
              ((= cp 11369) (integer->char (+ cp 1)))
              ((= cp 11371) (integer->char (+ cp 1)))
              ((= cp 11373) (integer->char (+ cp -10780)))
              ((= cp 11374) (integer->char (+ cp -10749)))
              ((= cp 11375) (integer->char (+ cp -10783)))
              ((= cp 11376) (integer->char (+ cp -10782)))
              ((= cp 11378) (integer->char (+ cp 1)))
              ((= cp 11381) (integer->char (+ cp 1)))
              ((<= 11390 cp 11391) (integer->char (+ cp -10815)))
              ((= cp 11392) (integer->char (+ cp 1)))
              ((= cp 11394) (integer->char (+ cp 1)))
              ((= cp 11396) (integer->char (+ cp 1)))
              ((= cp 11398) (integer->char (+ cp 1)))
              ((= cp 11400) (integer->char (+ cp 1)))
              ((= cp 11402) (integer->char (+ cp 1)))
              ((= cp 11404) (integer->char (+ cp 1)))
              ((= cp 11406) (integer->char (+ cp 1)))
              ((= cp 11408) (integer->char (+ cp 1)))
              ((= cp 11410) (integer->char (+ cp 1)))
              ((= cp 11412) (integer->char (+ cp 1)))
              ((= cp 11414) (integer->char (+ cp 1)))
              ((= cp 11416) (integer->char (+ cp 1)))
              ((= cp 11418) (integer->char (+ cp 1)))
              ((= cp 11420) (integer->char (+ cp 1)))
              ((= cp 11422) (integer->char (+ cp 1)))
              ((= cp 11424) (integer->char (+ cp 1)))
              ((= cp 11426) (integer->char (+ cp 1)))
              ((= cp 11428) (integer->char (+ cp 1)))
              ((= cp 11430) (integer->char (+ cp 1)))
              ((= cp 11432) (integer->char (+ cp 1)))
              ((= cp 11434) (integer->char (+ cp 1)))
              ((= cp 11436) (integer->char (+ cp 1)))
              ((= cp 11438) (integer->char (+ cp 1)))
              ((= cp 11440) (integer->char (+ cp 1)))
              ((= cp 11442) (integer->char (+ cp 1)))
              ((= cp 11444) (integer->char (+ cp 1)))
              ((= cp 11446) (integer->char (+ cp 1)))
              ((= cp 11448) (integer->char (+ cp 1)))
              ((= cp 11450) (integer->char (+ cp 1)))
              ((= cp 11452) (integer->char (+ cp 1)))
              ((= cp 11454) (integer->char (+ cp 1)))
              ((= cp 11456) (integer->char (+ cp 1)))
              ((= cp 11458) (integer->char (+ cp 1)))
              ((= cp 11460) (integer->char (+ cp 1)))
              ((= cp 11462) (integer->char (+ cp 1)))
              ((= cp 11464) (integer->char (+ cp 1)))
              ((= cp 11466) (integer->char (+ cp 1)))
              ((= cp 11468) (integer->char (+ cp 1)))
              ((= cp 11470) (integer->char (+ cp 1)))
              ((= cp 11472) (integer->char (+ cp 1)))
              ((= cp 11474) (integer->char (+ cp 1)))
              ((= cp 11476) (integer->char (+ cp 1)))
              ((= cp 11478) (integer->char (+ cp 1)))
              ((= cp 11480) (integer->char (+ cp 1)))
              ((= cp 11482) (integer->char (+ cp 1)))
              ((= cp 11484) (integer->char (+ cp 1)))
              ((= cp 11486) (integer->char (+ cp 1)))
              ((= cp 11488) (integer->char (+ cp 1)))
              ((= cp 11490) (integer->char (+ cp 1)))
              ((= cp 11499) (integer->char (+ cp 1)))
              ((= cp 11501) (integer->char (+ cp 1)))
              ((= cp 11506) (integer->char (+ cp 1)))
              ((= cp 42560) (integer->char (+ cp 1)))
              ((= cp 42562) (integer->char (+ cp 1)))
              ((= cp 42564) (integer->char (+ cp 1)))
              ((= cp 42566) (integer->char (+ cp 1)))
              ((= cp 42568) (integer->char (+ cp 1)))
              ((= cp 42570) (integer->char (+ cp 1)))
              ((= cp 42572) (integer->char (+ cp 1)))
              ((= cp 42574) (integer->char (+ cp 1)))
              ((= cp 42576) (integer->char (+ cp 1)))
              ((= cp 42578) (integer->char (+ cp 1)))
              ((= cp 42580) (integer->char (+ cp 1)))
              ((= cp 42582) (integer->char (+ cp 1)))
              ((= cp 42584) (integer->char (+ cp 1)))
              ((= cp 42586) (integer->char (+ cp 1)))
              ((= cp 42588) (integer->char (+ cp 1)))
              ((= cp 42590) (integer->char (+ cp 1)))
              ((= cp 42592) (integer->char (+ cp 1)))
              ((= cp 42594) (integer->char (+ cp 1)))
              ((= cp 42596) (integer->char (+ cp 1)))
              ((= cp 42598) (integer->char (+ cp 1)))
              ((= cp 42600) (integer->char (+ cp 1)))
              ((= cp 42602) (integer->char (+ cp 1)))
              ((= cp 42604) (integer->char (+ cp 1)))
              ((= cp 42624) (integer->char (+ cp 1)))
              ((= cp 42626) (integer->char (+ cp 1)))
              ((= cp 42628) (integer->char (+ cp 1)))
              ((= cp 42630) (integer->char (+ cp 1)))
              ((= cp 42632) (integer->char (+ cp 1)))
              ((= cp 42634) (integer->char (+ cp 1)))
              ((= cp 42636) (integer->char (+ cp 1)))
              ((= cp 42638) (integer->char (+ cp 1)))
              ((= cp 42640) (integer->char (+ cp 1)))
              ((= cp 42642) (integer->char (+ cp 1)))
              ((= cp 42644) (integer->char (+ cp 1)))
              ((= cp 42646) (integer->char (+ cp 1)))
              ((= cp 42648) (integer->char (+ cp 1)))
              ((= cp 42650) (integer->char (+ cp 1)))
              ((= cp 42786) (integer->char (+ cp 1)))
              ((= cp 42788) (integer->char (+ cp 1)))
              ((= cp 42790) (integer->char (+ cp 1)))
              ((= cp 42792) (integer->char (+ cp 1)))
              ((= cp 42794) (integer->char (+ cp 1)))
              ((= cp 42796) (integer->char (+ cp 1)))
              ((= cp 42798) (integer->char (+ cp 1)))
              ((= cp 42802) (integer->char (+ cp 1)))
              ((= cp 42804) (integer->char (+ cp 1)))
              ((= cp 42806) (integer->char (+ cp 1)))
              ((= cp 42808) (integer->char (+ cp 1)))
              ((= cp 42810) (integer->char (+ cp 1)))
              ((= cp 42812) (integer->char (+ cp 1)))
              ((= cp 42814) (integer->char (+ cp 1)))
              ((= cp 42816) (integer->char (+ cp 1)))
              ((= cp 42818) (integer->char (+ cp 1)))
              ((= cp 42820) (integer->char (+ cp 1)))
              ((= cp 42822) (integer->char (+ cp 1)))
              ((= cp 42824) (integer->char (+ cp 1)))
              ((= cp 42826) (integer->char (+ cp 1)))
              ((= cp 42828) (integer->char (+ cp 1)))
              ((= cp 42830) (integer->char (+ cp 1)))
              ((= cp 42832) (integer->char (+ cp 1)))
              ((= cp 42834) (integer->char (+ cp 1)))
              ((= cp 42836) (integer->char (+ cp 1)))
              ((= cp 42838) (integer->char (+ cp 1)))
              ((= cp 42840) (integer->char (+ cp 1)))
              ((= cp 42842) (integer->char (+ cp 1)))
              ((= cp 42844) (integer->char (+ cp 1)))
              ((= cp 42846) (integer->char (+ cp 1)))
              ((= cp 42848) (integer->char (+ cp 1)))
              ((= cp 42850) (integer->char (+ cp 1)))
              ((= cp 42852) (integer->char (+ cp 1)))
              ((= cp 42854) (integer->char (+ cp 1)))
              ((= cp 42856) (integer->char (+ cp 1)))
              ((= cp 42858) (integer->char (+ cp 1)))
              ((= cp 42860) (integer->char (+ cp 1)))
              ((= cp 42862) (integer->char (+ cp 1)))
              ((= cp 42873) (integer->char (+ cp 1)))
              ((= cp 42875) (integer->char (+ cp 1)))
              ((= cp 42877) (integer->char (+ cp -35332)))
              ((= cp 42878) (integer->char (+ cp 1)))
              ((= cp 42880) (integer->char (+ cp 1)))
              ((= cp 42882) (integer->char (+ cp 1)))
              ((= cp 42884) (integer->char (+ cp 1)))
              ((= cp 42886) (integer->char (+ cp 1)))
              ((= cp 42891) (integer->char (+ cp 1)))
              ((= cp 42893) (integer->char (+ cp -42280)))
              ((= cp 42896) (integer->char (+ cp 1)))
              ((= cp 42898) (integer->char (+ cp 1)))
              ((= cp 42902) (integer->char (+ cp 1)))
              ((= cp 42904) (integer->char (+ cp 1)))
              ((= cp 42906) (integer->char (+ cp 1)))
              ((= cp 42908) (integer->char (+ cp 1)))
              ((= cp 42910) (integer->char (+ cp 1)))
              ((= cp 42912) (integer->char (+ cp 1)))
              ((= cp 42914) (integer->char (+ cp 1)))
              ((= cp 42916) (integer->char (+ cp 1)))
              ((= cp 42918) (integer->char (+ cp 1)))
              ((= cp 42920) (integer->char (+ cp 1)))
              ((= cp 42922) (integer->char (+ cp -42308)))
              ((= cp 42923) (integer->char (+ cp -42319)))
              ((= cp 42924) (integer->char (+ cp -42315)))
              ((= cp 42925) (integer->char (+ cp -42305)))
              ((= cp 42926) (integer->char (+ cp -42308)))
              ((= cp 42928) (integer->char (+ cp -42258)))
              ((= cp 42929) (integer->char (+ cp -42282)))
              ((= cp 42930) (integer->char (+ cp -42261)))
              ((= cp 42931) (integer->char (+ cp 928)))
              ((= cp 42932) (integer->char (+ cp 1)))
              ((= cp 42934) (integer->char (+ cp 1)))
              ((= cp 42936) (integer->char (+ cp 1)))
              ((= cp 42938) (integer->char (+ cp 1)))
              ((= cp 42940) (integer->char (+ cp 1)))
              ((= cp 42942) (integer->char (+ cp 1)))
              ((= cp 42944) (integer->char (+ cp 1)))
              ((= cp 42946) (integer->char (+ cp 1)))
              ((= cp 42948) (integer->char (+ cp -48)))
              ((= cp 42949) (integer->char (+ cp -42307)))
              ((= cp 42950) (integer->char (+ cp -35384)))
              ((= cp 42951) (integer->char (+ cp 1)))
              ((= cp 42953) (integer->char (+ cp 1)))
              ((= cp 42955) (integer->char (+ cp -42343)))
              ((= cp 42956) (integer->char (+ cp 1)))
              ((= cp 42960) (integer->char (+ cp 1)))
              ((= cp 42966) (integer->char (+ cp 1)))
              ((= cp 42968) (integer->char (+ cp 1)))
              ((= cp 42970) (integer->char (+ cp 1)))
              ((= cp 42972) (integer->char (+ cp -42561)))
              ((= cp 42997) (integer->char (+ cp 1)))
              ((<= 65313 cp 65338) (integer->char (+ cp 32)))
              ((<= 66560 cp 66599) (integer->char (+ cp 40)))
              ((<= 66736 cp 66771) (integer->char (+ cp 40)))
              ((<= 66928 cp 66938) (integer->char (+ cp 39)))
              ((<= 66940 cp 66954) (integer->char (+ cp 39)))
              ((<= 66956 cp 66962) (integer->char (+ cp 39)))
              ((<= 66964 cp 66965) (integer->char (+ cp 39)))
              ((<= 68736 cp 68786) (integer->char (+ cp 64)))
              ((<= 68944 cp 68965) (integer->char (+ cp 32)))
              ((<= 71840 cp 71871) (integer->char (+ cp 32)))
              ((<= 93760 cp 93791) (integer->char (+ cp 32)))
              ((<= 125184 cp 125217) (integer->char (+ cp 34)))
              (else char)
        ) ;cond
      ) ;let
    ) ;define

    (define (char-foldcase char)
      (unless (char? char)
        (error 'type-error "char-foldcase: parameter must be character")
      ) ;unless
      (char-downcase char)
    ) ;define

    (define s7-char-numeric? char-numeric?)

    (define (char-numeric? char)
      (unless (char? char)
        (error 'type-error "char-numeric?: parameter must be character")
      ) ;unless
      (s7-char-numeric? char)
    ) ;define

    (define s7-char-alphabetic? char-alphabetic?)

    (define (char-alphabetic? char)
      (unless (char? char)
        (error 'type-error "char-alphabetic?: parameter must be character")
      ) ;unless
      (s7-char-alphabetic? char)
    ) ;define

    (define s7-char-whitespace? char-whitespace?)

    (define (char-whitespace? char)
      (unless (char? char)
        (error 'type-error "char-whitespace?: parameter must be character")
      ) ;unless
      (s7-char-whitespace? char)
    ) ;define

    (define s7-char-upper-case? char-upper-case?)

    (define (char-upper-case? char)
      (unless (char? char)
        (error 'type-error "char-upper-case?: parameter must be character")
      ) ;unless
      (s7-char-upper-case? char)
    ) ;define

    (define s7-char-lower-case? char-lower-case?)

    (define (char-lower-case? char)
      (unless (char? char)
        (error 'type-error "char-lower-case?: parameter must be character")
      ) ;unless
      (s7-char-lower-case? char)
    ) ;define

    (define s7-char-ci=? char-ci=?)

    (define (char-ci=? char1 char2 . rest)
      (unless (char? char1)
        (error 'type-error "char-ci=?: first parameter must be character")
      ) ;unless
      (unless (char? char2)
        (error 'type-error "char-ci=?: second parameter must be character")
      ) ;unless
      (let loop
        ((current (s7-char-ci=? char1 char2)) (remaining rest))
        (if (null? remaining)
          current
          (let ((next-char (car remaining)))
            (unless (char? next-char)
              (error 'type-error "char-ci=?: parameter must be character")
            ) ;unless
            (and current (loop (s7-char-ci=? char2 next-char) (cdr remaining)))
          ) ;let
        ) ;if
      ) ;let
    ) ;define

    (define s7-char-ci<? char-ci<?)

    (define (char-ci<? char1 char2 . rest)
      (unless (char? char1)
        (error 'type-error "char-ci<?: first parameter must be character")
      ) ;unless
      (unless (char? char2)
        (error 'type-error "char-ci<?: second parameter must be character")
      ) ;unless
      (let loop
        ((current (s7-char-ci<? char1 char2)) (remaining rest))
        (if (null? remaining)
          current
          (let ((next-char (car remaining)))
            (unless (char? next-char)
              (error 'type-error "char-ci<?: parameter must be character")
            ) ;unless
            (and current (loop (s7-char-ci<? char2 next-char) (cdr remaining)))
          ) ;let
        ) ;if
      ) ;let
    ) ;define

    (define s7-char-ci>? char-ci>?)

    (define (char-ci>? char1 char2 . rest)
      (unless (char? char1)
        (error 'type-error "char-ci>?: first parameter must be character")
      ) ;unless
      (unless (char? char2)
        (error 'type-error "char-ci>?: second parameter must be character")
      ) ;unless
      (let loop
        ((current (s7-char-ci>? char1 char2)) (remaining rest))
        (if (null? remaining)
          current
          (let ((next-char (car remaining)))
            (unless (char? next-char)
              (error 'type-error "char-ci>?: parameter must be character")
            ) ;unless
            (and current (loop (s7-char-ci>? char2 next-char) (cdr remaining)))
          ) ;let
        ) ;if
      ) ;let
    ) ;define

    (define s7-char-ci>=? char-ci>=?)

    (define (char-ci>=? char1 char2 . rest)
      (unless (char? char1)
        (error 'type-error "char-ci>=?: first parameter must be character")
      ) ;unless
      (unless (char? char2)
        (error 'type-error "char-ci>=?: second parameter must be character")
      ) ;unless
      (let loop
        ((current (s7-char-ci>=? char1 char2)) (remaining rest))
        (if (null? remaining)
          current
          (let ((next-char (car remaining)))
            (unless (char? next-char)
              (error 'type-error "char-ci>=?: parameter must be character")
            ) ;unless
            (and current (loop (s7-char-ci>=? char2 next-char) (cdr remaining)))
          ) ;let
        ) ;if
      ) ;let
    ) ;define

    (define s7-char-ci<=? char-ci<=?)

    (define (char-ci<=? char1 char2 . rest)
      (unless (char? char1)
        (error 'type-error "char-ci<=?: first parameter must be character")
      ) ;unless
      (unless (char? char2)
        (error 'type-error "char-ci<=?: second parameter must be character")
      ) ;unless
      (let loop
        ((current (s7-char-ci<=? char1 char2)) (remaining rest))
        (if (null? remaining)
          current
          (let ((next-char (car remaining)))
            (unless (char? next-char)
              (error 'type-error "char-ci<=?: parameter must be character")
            ) ;unless
            (and current (loop (s7-char-ci<=? char2 next-char) (cdr remaining)))
          ) ;let
        ) ;if
      ) ;let
    ) ;define

    (define s7-string-ci=? string-ci=?)

    (define (string-ci=? str1 str2 . rest)
      (unless (string? str1)
        (error 'type-error "string-ci=?: first parameter must be string")
      ) ;unless
      (unless (string? str2)
        (error 'type-error "string-ci=?: second parameter must be string")
      ) ;unless
      (let loop
        ((current (s7-string-ci=? str1 str2)) (remaining rest))
        (if (null? remaining)
          current
          (let ((next-str (car remaining)))
            (unless (string? next-str)
              (error 'type-error "string-ci=?: parameter must be string")
            ) ;unless
            (and current (loop (s7-string-ci=? str2 next-str) (cdr remaining)))
          ) ;let
        ) ;if
      ) ;let
    ) ;define

    (define s7-string-ci<? string-ci<?)

    (define (string-ci<? str1 str2 . rest)
      (unless (string? str1)
        (error 'type-error "string-ci<?: first parameter must be string")
      ) ;unless
      (unless (string? str2)
        (error 'type-error "string-ci<?: second parameter must be string")
      ) ;unless
      (let loop
        ((current (s7-string-ci<? str1 str2)) (remaining rest))
        (if (null? remaining)
          current
          (let ((next-str (car remaining)))
            (unless (string? next-str)
              (error 'type-error "string-ci<?: parameter must be string")
            ) ;unless
            (and current (loop (s7-string-ci<? str2 next-str) (cdr remaining)))
          ) ;let
        ) ;if
      ) ;let
    ) ;define

    (define s7-string-ci>? string-ci>?)

    (define (string-ci>? str1 str2 . rest)
      (unless (string? str1)
        (error 'type-error "string-ci>?: first parameter must be string")
      ) ;unless
      (unless (string? str2)
        (error 'type-error "string-ci>?: second parameter must be string")
      ) ;unless
      (let loop
        ((current (s7-string-ci>? str1 str2)) (remaining rest))
        (if (null? remaining)
          current
          (let ((next-str (car remaining)))
            (unless (string? next-str)
              (error 'type-error "string-ci>?: parameter must be string")
            ) ;unless
            (and current (loop (s7-string-ci>? str2 next-str) (cdr remaining)))
          ) ;let
        ) ;if
      ) ;let
    ) ;define

    (define s7-string-ci<=? string-ci<=?)

    (define (string-ci<=? str1 str2 . rest)
      (unless (string? str1)
        (error 'type-error "string-ci<=?: first parameter must be string")
      ) ;unless
      (unless (string? str2)
        (error 'type-error "string-ci<=?: second parameter must be string")
      ) ;unless
      (let loop
        ((current (s7-string-ci<=? str1 str2)) (remaining rest))
        (if (null? remaining)
          current
          (let ((next-str (car remaining)))
            (unless (string? next-str)
              (error 'type-error "string-ci<=?: parameter must be string")
            ) ;unless
            (and current (loop (s7-string-ci<=? str2 next-str) (cdr remaining)))
          ) ;let
        ) ;if
      ) ;let
    ) ;define

    (define s7-string-ci>=? string-ci>=?)

    (define (string-ci>=? str1 str2 . rest)
      (unless (string? str1)
        (error 'type-error "string-ci>=?: first parameter must be string")
      ) ;unless
      (unless (string? str2)
        (error 'type-error "string-ci>=?: second parameter must be string")
      ) ;unless
      (let loop
        ((current (s7-string-ci>=? str1 str2)) (remaining rest))
        (if (null? remaining)
          current
          (let ((next-str (car remaining)))
            (unless (string? next-str)
              (error 'type-error "string-ci>=?: parameter must be string")
            ) ;unless
            (and current (loop (s7-string-ci>=? str2 next-str) (cdr remaining)))
          ) ;let
        ) ;if
      ) ;let
    ) ;define

    (define s7-string-upcase string-upcase)

    (define (string-upcase str)
      (unless (string? str)
        (error 'type-error "string-upcase: parameter must be string")
      ) ;unless
      (s7-string-upcase str)
    ) ;define

    (define s7-string-downcase string-downcase)

    (define (string-downcase str)
      (unless (string? str)
        (error 'type-error "string-downcase: parameter must be string")
      ) ;unless
      (s7-string-downcase str)
    ) ;define

    (define (string-foldcase str)
      (unless (string? str)
        (error 'type-error "string-foldcase: parameter must be string")
      ) ;unless
      (string-downcase str)
    ) ;define

  ) ;begin
) ;define-library
