(define-library (native-scale compile)
  (export run-compile-workload run-compile-phases)
  (import (goldfish) (scheme base) (scheme write) (scheme file)
          (scheme process-context) (native-scale timing))
  (begin
    (define (compile-workload measure)
      (define source (get-environment-variable "GOLDFISH_BENCH_SOURCE"))
      (define artifact (string-append (gfo-dir) "/" (gfo-key source) "-o2.gfo"))
      (define warm? (string=? (get-environment-variable "GOLDFISH_BENCH_CASE") "compile-warm"))
      (unless (eqv? (file-exists? artifact) warm?)
        (error "benchmark compilation cache state mismatch" artifact))
      (let ((compiled (measure 'compile (lambda () (compile-file-cached source)))))
        (unless (and (pair? compiled) (eq? (car compiled) 'begin))
          (error "benchmark compiler did not return a lowered program")))
      (unless (file-exists? artifact)
        (error "benchmark compiler did not write cache artifact" artifact))
      'BENCH-OK)
    (define (run-compile-workload)
      (compile-workload (lambda (label thunk) (thunk))))
    (define (run-compile-phases) (compile-workload phase-measure))))
