(define-library (native-scale set)
  (export run-set-workload run-set-phases)
  (import (scheme base) (scheme process-context) (liii set) (native-scale timing))
  (begin
    (define (set-workload measure)
      (let ((n (string->number (get-environment-variable "GOLDFISH_BENCH_SIZE"))))
        (unless (and (integer? n) (exact? n) (> n 0))
          (error "invalid benchmark size"))
        (let* ((xs (measure 'list-build
                     (lambda ()
                       (let loop ((i (- n 1)) (xs '()))
                         (if (< i 0) xs (loop (- i 1) (cons i xs)))))))
               (s (measure 'set-build (lambda () (list->set xs)))))
          (measure 'check
            (lambda ()
              (unless (and (= (set-size s) n) (set-contains? s (- n 1))
                           (not (set-contains? s n)))
                (error "benchmark set check failed")))))
        'BENCH-OK))
    (define (run-set-workload)
      (set-workload (lambda (label thunk) (thunk))))
    (define (run-set-phases) (set-workload phase-measure))))
