(define-library (native-scale set)
  (export run-set-workload)
  (import (scheme base) (scheme process-context) (liii set))
  (begin
    (define (run-set-workload)
      (let ((n (string->number (get-environment-variable "GOLDFISH_BENCH_SIZE"))))
        (unless (and (integer? n) (exact? n) (> n 0))
          (error "invalid benchmark size"))
        (let* ((xs (let loop ((i (- n 1)) (xs '()))
                     (if (< i 0) xs (loop (- i 1) (cons i xs)))))
               (s (list->set xs)))
          (unless (and (= (set-size s) n) (set-contains? s (- n 1))
                       (not (set-contains? s n)))
            (error "benchmark set check failed")))
        'BENCH-OK))
  ))
