(define-library (native-scale timing)
  (export phase-measure phase-startup phase-begin phase-finish)
  (import (scheme base) (scheme write) (scheme time) (scheme process-context))
  (begin
    (define (phase-row label elapsed)
      (display "PHASE\t") (display label) (display "\t")
      (display (inexact (/ elapsed 1000000000))) (newline)
      (flush-output-port (current-output-port)))
    (define (phase-startup)
      (phase-row 'startup-and-timer-import
                 (- (monotonic-nanosecond)
                    (string->number
                      (get-environment-variable "GOLDFISH_BENCH_START_NS")))))
    (define (phase-begin label)
      (display "PHASE-BEGIN\t") (display label) (newline)
      (flush-output-port (current-output-port))
      (monotonic-nanosecond))
    (define (phase-finish label start)
      (phase-row label (- (monotonic-nanosecond) start)))
    (define (phase-measure label thunk)
      (let* ((start (phase-begin label))
             (result (thunk)))
        (phase-finish label start)
        result))))
