(define-library (native-scale workloads)
  (export run-scale-workload)
  (import (scheme base) (scheme write) (scheme process-context))
  (begin
    (define (run-scale-workload)
      
      (define n (string->number (get-environment-variable "GOLDFISH_BENCH_SIZE")))
      (define workload (string->symbol (get-environment-variable "GOLDFISH_BENCH_CASE")))
      
      (define (ensure value) (unless value (error "benchmark semantic check failed" workload)))
      (define (range n)
        (let loop ((i (- n 1)) (xs '()))
          (if (< i 0) xs (loop (- i 1) (cons i xs)))))
      (define (deep n)
        (let loop ((i n) (x 'leaf))
          (if (= i 0) x (loop (- i 1) (vector i x)))))
      
      (unless (and (integer? n) (exact? n) (> n 0)) (error "invalid benchmark size"))
      
      (case workload
        ((allocation)
         (let loop ((i 0) (last #()))
           (if (= i 50)
               (ensure (and (= (vector-length last) n) (= (vector-ref last 0) 49)))
               (loop (+ i 1) (make-vector n i)))))
        ((long-list)
         (let ((xs (range n)))
           (ensure (list? xs))
           (ensure (= (length xs) n))
           (ensure (= (car (reverse xs)) (- n 1)))))
        ((wide-vector)
         (let ((v (make-vector n 0)))
           (do ((i 0 (+ i 1))) ((= i n)) (vector-set! v i i))
           (let ((copy (vector-copy v)))
             (ensure (= (vector-length copy) n))
             (ensure (= (vector-ref copy (- n 1)) (- n 1))))))
        ((deep-structure)
         (let ((a (deep n)) (b (deep n)))
           (ensure (equal? a b))
           (let loop ((x a) (depth 0))
             (if (vector? x)
                 (loop (vector-ref x 1) (+ depth 1))
                 (ensure (and (eq? x 'leaf) (= depth n)))))))
        (else (error "unknown benchmark workload" workload)))
      'BENCH-OK)
  ))
