(letrec
  ((loop
    (lambda (i end acc count)
      (if (> i end)
        (cons count acc)
        (let ((c (integer->char i)))
          (if (char-numeric? c)
            (loop (+ i 1) end (cons c acc) (+ count 1))
            (loop (+ i 1) end acc count)))))))

  ;; BMP: 0x0000 - 0xD7FF
  (let ((r1 (loop 0 #xD7FF '() 0)))
    ;; SMP-SPU: 0xE000 - 0x10FFFF
    (let ((r2 (loop #xE000 #x10FFFF (cdr r1) (car r1))))
      (let ((count (car r2))
            (chars (cdr r2)))
        (display "codepoint,char,category")
        (newline)
        (for-each
          (lambda (c)
            (let ((i (char->integer c)))
              (display "U+")
              (if (< i #x1000)
                (if (< i #x100)
                  (if (< i #x10)
                    (display (string-append "000" (number->string i 16)))
                    (display (string-append "00" (number->string i 16))))
                  (display (string-append "0" (number->string i 16))))
                (display (number->string i 16)))
              (display ",")
              (display c)
              (display ",")
              (cond
                ((<= #x30 i #x39) (display "ASCII Digit"))
                ((<= #x660 i #x669) (display "Arabic-Indic Digit"))
                ((<= #x6F0 i #x6F9) (display "Extended Arabic-Indic Digit"))
                ((<= #x966 i #x96F) (display "Devanagari Digit"))
                ((<= #x9E6 i #x9EF) (display "Bengali Digit"))
                ((<= #xA66 i #xA6F) (display "Gurmukhi Digit"))
                ((<= #xAE6 i #xAEF) (display "Gujarati Digit"))
                ((<= #xB66 i #xB6F) (display "Oriya Digit"))
                ((<= #xBE6 i #xBEF) (display "Tamil Digit"))
                ((<= #xC66 i #xC6F) (display "Telugu Digit"))
                ((<= #xCE6 i #xCEF) (display "Kannada Digit"))
                ((<= #xD66 i #xD6F) (display "Malayalam Digit"))
                ((<= #xE50 i #xE59) (display "Thai Digit"))
                ((<= #xED0 i #xED9) (display "Lao Digit"))
                ((<= #xF20 i #xF29) (display "Tibetan Digit"))
                ((<= #x1040 i #x1049) (display "Myanmar Digit"))
                ((<= #x17E0 i #x17E9) (display "Khmer Digit"))
                ((<= #x1810 i #x1819) (display "Mongolian Digit"))
                ((<= #x1946 i #x194F) (display "Limbu Digit"))
                ((<= #x19D0 i #x19D9) (display "New Tai Lue Digit"))
                ((<= #x1A80 i #x1A89) (display "Tai Tham Hora Digit"))
                ((<= #x1A90 i #x1A99) (display "Tai Tham Tham Digit"))
                ((<= #x1B50 i #x1B59) (display "Balinese Digit"))
                ((<= #x1BB0 i #x1BB9) (display "Sundanese Digit"))
                ((<= #x1C40 i #x1C49) (display "Lepcha Digit"))
                ((<= #x1C50 i #x1C59) (display "Ol Chiki Digit"))
                ((<= #xA620 i #xA629) (display "Vai Digit"))
                ((<= #xA8D0 i #xA8D9) (display "Saurashtra Digit"))
                ((<= #xA900 i #xA909) (display "Kayah Li Digit"))
                ((<= #xA9D0 i #xA9D9) (display "Javanese Digit"))
                ((<= #xA9F0 i #xA9F9) (display "Myanmar Tai Laing Digit"))
                ((<= #xAA50 i #xAA59) (display "Cham Digit"))
                ((<= #xABF0 i #xABF9) (display "Meetei Mayek Digit"))
                ((<= #xFF10 i #xFF19) (display "Fullwidth Digit"))
                ((<= #x104A0 i #x104A9) (display "Osmanya Digit"))
                ((<= #x11066 i #x1106F) (display "Brahmi Digit"))
                ((<= #x110F0 i #x110F9) (display "Sora Sompeng Digit"))
                ((<= #x11136 i #x1113F) (display "Chakma Digit"))
                ((<= #x111D0 i #x111D9) (display "Sharada Digit"))
                ((<= #x112F0 i #x112F9) (display "Khudawadi Digit"))
                ((<= #x11450 i #x11459) (display "Newa Digit"))
                ((<= #x114D0 i #x114D9) (display "Tirhuta Digit"))
                ((<= #x11650 i #x11659) (display "Modi Digit"))
                ((<= #x116C0 i #x116C9) (display "Takri Digit"))
                ((<= #x11730 i #x11739) (display "Ahom Digit"))
                ((<= #x118E0 i #x118E9) (display "Warang Citi Digit"))
                ((<= #x11C50 i #x11C59) (display "Bhaiksuki Digit"))
                ((<= #x11D50 i #x11D59) (display "Masaram Gondi Digit"))
                ((<= #x16A60 i #x16A69) (display "Mro Digit"))
                ((<= #x16B50 i #x16B59) (display "Pahawh Hmong Digit"))
                ((<= #x1D7CE i #x1D7FF) (display "Mathematical Digit"))
                ((<= #x1E140 i #x1E149) (display "Nyiakeng Puachue Hmong Digit"))
                ((<= #x1E2F0 i #x1E2F9) (display "Wancho Digit"))
                ((<= #x1E950 i #x1E959) (display "Adlam Digit"))
                ((<= #x1FBF0 i #x1FBF9) (display "Segmented Digit"))
                ((<= #x2070 i #x2079) (display "Superscript"))
                ((<= #x2080 i #x2089) (display "Subscript"))
                ((<= #x3021 i #x3029) (display "Hangzhou"))
                ((<= #x3038 i #x303A) (display "Hangzhou"))
                ((<= #x3220 i #x3229) (display "Parenthesized"))
                ((<= #x3251 i #x325F) (display "Circled >= 21"))
                ((<= #x3280 i #x3289) (display "Circled"))
                ((<= #x32B1 i #x32BF) (display "Circled >= 21"))
                ((<= #x3358 i #x3370) (display "Ideographic Time"))
                ((<= #x33E0 i #x33FE) (display "Ideographic Tally"))
                ((<= #xA6E6 i #xA6EF) (display "Bamum"))
                ((<= #x10107 i #x10133) (display "Aegean"))
                ((<= #x10145 i #x1014A) (display "Greek Acrophonic"))
                ((<= #x10175 i #x10178) (display "Greek Fraction"))
                ((<= #x1018A i #x1018B) (display "Greek"))
                ((<= #x102E1 i #x102FB) (display "Coptic Epact"))
                ((<= #x10320 i #x10323) (display "Old Italic"))
                ((<= #x10341 i #x10341) (display "Gothic"))
                ((<= #x1034A i #x1034A) (display "Gothic"))
                ((<= #x103D1 i #x103D5) (display "Old Persian"))
                ((<= #x104A0 i #x104A9) (display "Osmanya"))
                ((<= #x10858 i #x1085F) (display "Aramaic"))
                ((<= #x10879 i #x1087F) (display "Nabataean"))
                ((<= #x108A7 i #x108AF) (display "Palmyrene"))
                ((<= #x108FB i #x108FF) (display "Hatran"))
                ((<= #x10916 i #x1091B) (display "Phoenician"))
                ((<= #x109BC i #x109BD) (display "Meroitic Cursive"))
                ((<= #x109C0 i #x109CF) (display "Meroitic Hieroglyphs"))
                ((<= #x10A40 i #x10A47) (display "Kharosthi"))
                ((<= #x10A7D i #x10A83) (display "Old South Arabian"))
                ((<= #x10A9D i #x10A9F) (display "Old North Arabian"))
                ((<= #x10AC5 i #x10AC8) (display "Manichaean"))
                ((<= #x10AD7 i #x10AD8) (display "Manichaean"))
                ((<= #x10AEB i #x10AEF) (display "Manichaean"))
                ((<= #x10B58 i #x10B5F) (display "Inscriptional Parthian"))
                ((<= #x10B78 i #x10B7F) (display "Inscriptional Pahlavi"))
                ((<= #x10BA9 i #x10BAF) (display "Psalter Pahlavi"))
                ((<= #x10CFA i #x10CFF) (display "Old Hungarian"))
                ((<= #x10D30 i #x10D39) (display "Hanifi Rohingya"))
                ((<= #x10E60 i #x10E7E) (display "Rumi"))
                ((<= #x10EAB i #x10EAC) (display "Yezidi"))
                ((<= #x10F1D i #x10F26) (display "Old Sogdian"))
                ((<= #x10F51 i #x10F54) (display "Sogdian"))
                ((<= #x10F5A i #x10F6B) (display "Chorasmian"))
                ((<= #x10FB5 i #x10FC4) (display "Sogdian"))
                ((<= #x10FC5 i #x10FCB) (display "Old Uyghur"))
                ((<= #x11052 i #x1106F) (display "Brahmi Number"))
                ((<= #x110F0 i #x110F9) (display "Sora Sompeng"))
                ((<= #x11136 i #x1113F) (display "Chakma"))
                ((<= #x111E1 i #x111F4) (display "Sinhala Archaic"))
                ((<= #x112F0 i #x112F9) (display "Khudawadi"))
                ((<= #x11450 i #x11459) (display "Newa"))
                ((<= #x114D0 i #x114D9) (display "Tirhuta"))
                ((<= #x11650 i #x11659) (display "Modi"))
                ((<= #x116C0 i #x116C9) (display "Takri"))
                ((<= #x11730 i #x11739) (display "Ahom"))
                ((<= #x118E0 i #x118E9) (display "Warang Citi"))
                ((<= #x11950 i #x11959) (display "Dives Akuru"))
                ((<= #x11C50 i #x11C59) (display "Bhaiksuki"))
                ((<= #x11D50 i #x11D59) (display "Masaram Gondi"))
                ((<= #x11DA0 i #x11DA9) (display "Gunjala Gondi"))
                ((<= #x11F50 i #x11F59) (display "Kawi"))
                ((<= #x11FC0 i #x11FD4) (display "Tamil Fraction"))
                ((<= #x12400 i #x1246E) (display "Cuneiform"))
                ((<= #x16A60 i #x16A69) (display "Mro"))
                ((<= #x16AC0 i #x16AC9) (display "Tangsa"))
                ((<= #x16B50 i #x16B59) (display "Pahawh Hmong"))
                ((<= #x1D2E0 i #x1D2F3) (display "Mayan"))
                ((<= #x1D360 i #x1D371) (display "Counting Rod"))
                ((<= #x1E4D0 i #x1E4D9) (display "Nag Mundari"))
                ((<= #x1E5F1 i #x1E5FA) (display "Ol Onal"))
                ((<= #x1EC71 i #x1ECAB) (display "Indic Siyaq"))
                ((<= #x1ED01 i #x1ED2D) (display "Ottoman Siyaq"))
                ((<= #x1ED3D i #x1ED3F) (display "Ottoman Siyaq"))
                ((<= #x1F100 i #x1F10C) (display "Enclosed"))
                ((<= #x1F10D i #x1F10F) (display "Copyleft"))
                ((<= #x24EB i #x24FF) (display "Negative Circled"))
                ((<= #x2776 i #x2793) (display "Dingbat Circled"))
                ((<= #x2CFD i #x2CFD) (display "Coptic Fraction"))
                ((<= #x3007 i #x3007) (display "Ideographic Zero"))
                ((<= #x3021 i #x3029) (display "Hangzhou"))
                ((<= #x3038 i #x303A) (display "Hangzhou"))
                ((<= #x3192 i #x3195) (display "Ideographic Tally"))
                ((<= #x3220 i #x3229) (display "Parenthesized"))
                ((<= #x3251 i #x325F) (display "Circled 21+"))
                ((<= #x3280 i #x3289) (display "Circled"))
                ((<= #x32B1 i #x32BF) (display "Circled 21+"))
                ((<= #x3358 i #x3370) (display "Ideographic Time"))
                ((<= #x33E0 i #x33FE) (display "Ideographic Tally"))
                (else (display "Other")))
              (newline)))
          (reverse chars))))))
