(import (srfi srfi-125) (srfi srfi-128) (srfi srfi-78))
(check-set-mode! 'report-failed)
(check (hash-table? (make-hash-table (make-equal-comparator))) => #t)
(check (let ((ht (make-hash-table (make-equal-comparator)))) (hash-table-set! ht 'a 1) (hash-table-ref ht 'a)) => 1)
(check (let ((ht (make-hash-table (make-equal-comparator)))) (hash-table-set! ht 'a 1) (hash-table-contains? ht 'a)) => #t)
(check (let ((ht (make-hash-table (make-equal-comparator)))) (hash-table-size ht) ) => 0)
(check-report)
(if (check-failed?) (exit -1))
