(import (srfi srfi-113) (srfi srfi-128) (srfi srfi-78))
(check-set-mode! 'report-failed)
(check (set? (set (make-equal-comparator) 1 2 3)) => #t)
(check (set-size (set (make-equal-comparator) 1 2 3)) => 3)
(check (set-contains? (set (make-equal-comparator) 1 2 3) 2) => #t)
(check (set-contains? (set (make-equal-comparator) 1 2 3) 9) => #f)
(check (set-empty? (set (make-equal-comparator))) => #t)
(check (set-contains? (set (make-equal-comparator) 1 2 3) 1) => #t)
(check (set-contains? (set (make-equal-comparator) 1 2 3) 3) => #t)
(check-report)
(if (check-failed?) (exit -1))
