(import (scheme base) (liii bitwise) (liii check))
(check-set-mode! 'report-failed)

(check (list (bitwise-and) (bitwise-ior) (bitwise-xor) (bitwise-eqv)) => '(-1 0 0 -1))
(check (bitwise-eqv 7) => 7)
(check (bitwise-eqv 1 2 4) => 7)
(check (bitwise-eqv 1 2 4 8) => -16)
(check (list (integer-length -1) (integer-length -2) (integer-length -8)) => '(0 1 3))

(let* ((high (expt 2 130)) (mask (- high 1)) (value (+ high 37)))
  (check (arithmetic-shift 1 130) => high)
  (check (arithmetic-shift high -130) => 1)
  (check (arithmetic-shift (- value) -130) => -2)
  (check (arithmetic-shift (- high) -130) => -1)
  (check (arithmetic-shift (- high) 3) => (- (expt 2 133)))
  (check (bitwise-not value) => (- (+ value 1)))
  (check (bitwise-and value mask) => 37)
  (check (bitwise-and value -1) => value)
  (check (bitwise-ior value mask) => (- (* high 2) 1))
  (check (bitwise-xor value -1) => (bitwise-not value))
  (check (bitwise-xor (- high) (- (+ high 1))) => (- (* high 2) 1))
  (check (bit-count mask) => 130)
  (check (bit-count (- high)) => 130)
  (check (bit-count (- (+ high 1))) => 1)
  (check (integer-length high) => 131)
  (check (integer-length (- high)) => 130)
  (check (first-set-bit (- high)) => 130)
  (check (bit-set? 130 value) => #t)
  (check (bit-set? 131 value) => #f)
  (check (bit-set? (expt 2 100) -1) => #t)
  (check (bit-set? (expt 2 100) value) => #f)
  (check (copy-bit (expt 2 100) -1 #t) => -1)
  (check (copy-bit (expt 2 100) value #f) => value)
  (check (copy-bit 130 37 #t) => value)
  (check (copy-bit 130 value #f) => 37)
  (check (copy-bit 130 -1 #f) => (- (+ high 1)))
  (check (bit-swap 130 0 high) => 1)
  (check (bit-field value 130 131) => 1)
  (check (bit-field value 200 210) => 0)
  (check (bit-field -1 200 210) => 1023)
  (check (bit-field -1 130 130) => 0)
  (check (bit-field-every? 0 130 130) => #t)
  (check (bit-field-any? -1 130 130) => #f)
  (check (bit-field-clear -1 0 130) => (- high))
  (check (bit-field-set 0 0 130) => mask)
  (check (bitwise-if high value 7) => (+ high 7))
  (check (bit-field-replace 0 5 130 133) => (* high 5))
  (check (bit-field-replace-same -1 0 130 131) => (- (+ high 1)))
  (check (bit-field-rotate high 1 0 131) => 1)
  (check (bit-field-rotate 7 -1 1 4) => 11)
  (check (bit-field-rotate value (expt 2 100) 10 10) => value)
  (check (bit-field-reverse high 0 131) => 1)
  (check (list->bits (bits->list value)) => value)
  (check (vector->bits (bits->vector value)) => value))

(check (arithmetic-shift 3 -9223372036854775808) => 0)
(check (arithmetic-shift -3 -9223372036854775808) => -1)
(check (arithmetic-shift -3 (- (expt 2 100))) => -1)
(check (arithmetic-shift 0 (expt 2 100)) => 0)
(check (copy-bit 63 1 #t) => 9223372036854775809)
(check (copy-bit 63 -1 #f) => -9223372036854775809)
(check (bit-field 0 0 1) => 0)
(check (bits->list 6 5) => '(#f #t #t #f #f))
(check (bits->vector 6 4) => #(#f #t #t #f))
(check (bits) => 0)
(check (bits #f #t #t) => 6)
(check (bitwise-fold cons '() 87) => '(#t #f #t #f #t #t #t))
(let ((seen '()))
  (bitwise-for-each (lambda (bit) (set! seen (cons bit seen))) 6)
  (check (reverse seen) => '(#f #t #t)))
(check (bitwise-unfold (lambda (i) (= i 10)) even? (lambda (i) (+ i 1)) 0) => 341)
(let ((generator (make-bitwise-generator -2)))
  (check (list (generator) (generator) (generator) (generator)) => '(#f #t #t #t)))

;; Check sign extension independently through arithmetic division.
(do ((n -16 (+ n 1))) ((= n 16))
  (do ((index 0 (+ index 1))) ((= index 9))
    (check (bit-set? index n) => (odd? (floor (/ n (expt 2 index)))))))

(for-each
  (lambda (thunk) (check (guard (obj (else #t)) (thunk) #f) => #t))
  (list (lambda () (bitwise-and 1.0))
        (lambda () (bitwise-not 1/2))
        (lambda () (arithmetic-shift 1 2.0))
        (lambda () (bit-count 3.0))
        (lambda () (integer-length 3.0))
        (lambda () (bit-set? -1 1))
        (lambda () (copy-bit 1 0 'true))
        (lambda () (bit-field 1 5 4))
        (lambda () (bit-field-set 1 0 -1))
        (lambda () (bits->list -1))
        (lambda () (bits->list 1 -1))
        (lambda () (list->bits '(#t 1)))
        (lambda () (bitwise-fold #f 0 1))
        (lambda () (arithmetic-shift 1 (expt 2 100)))))

(check-report)
