(import (scheme base) (scheme write))
;; N-queens counting: backtracking over a vector, mixed vector / arithmetic
;; work, non-tail and tail recursion interleaved.
(define (safe? pos col row)
  (let loop ((i 0))
    (cond ((= i col) #t)
          ((or (= (vector-ref pos i) row)
               (= (- (vector-ref pos i) row) (- i col))
               (= (- row (vector-ref pos i)) (- i col))) #f)
          (else (loop (+ i 1))))))
(define (nqueens n)
  (let ((pos (make-vector n 0)))
    (let place ((col 0) (solutions 0))
      (if (= col n)
          (+ solutions 1)
          (let row-loop ((row 0) (solutions solutions))
            (cond ((>= row n) solutions)
                  ((safe? pos col row)
                   (vector-set! pos col row)
                   (row-loop (+ row 1) (place (+ col 1) solutions)))
                  (else (row-loop (+ row 1) solutions))))))))
(write (nqueens 9))
(newline)
