(import (liii check))
(import (scheme base))
(check-set-mode! 'report-failed)
;; null? 基本测试：空列表和非空列表
(check (null? '()) => #t)
(check (null? '(1)) => #f)
(check (null? '(a)) => #f)
(check (null? '(a b c)) => #f)
(check (null? '(1 2 3 4 5)) => #f)
;; null? 特殊结构和边界情况
(check (null? '(())) => #f)
(check (null? '(() () ())) => #f)
(check (null? '((a b) (c d))) => #f)
;; null? 非列表类型测试 - 全面覆盖
(check (null? #t) => #f)
(check (null? #f) => #f)
(check (null? 0) => #f)
(check (null? 123) => #f)
(check (null? -456) => #f)
(check (null? 3.14) => #f)
(check (null? "") => #f)
(check (null? "hello") => #f)
(check (null? '#()) => #f)
(check (null? '#(1 2 3)) => #f)
(check (null? 'symbol) => #f)
(check (null? '123) => #f)
(check (null? #\a) => #f)
;; null? 点对结构测试
(check (null? '(a . b)) => #f)
(check (null? (cons 1 2)) => #f)
;; null? 复杂表达式测试
(check (null? (list)) => #t)
(check (null? (append '() '())) => #t)
(check (null? (cdr '(a))) => #t)
(check (null? (cdr '(a b))) => #f)
;; null? 与列表操作结合测试
(check (null? (reverse '())) => #t)
(check (null? (reverse '(1))) => #f)
;; null? 错误处理测试
(check-catch 'wrong-number-of-args (null?))
(check-catch 'wrong-number-of-args (null? '() '()))
(check-catch 'wrong-number-of-args (null? 1 2))
(check-report)