(import (scheme base) (scheme read) (scheme write) (scheme file) (liii check))
(check-set-mode! 'report-failed)

;; Indexes count Unicode scalar values, independently of UTF-8 width.
(define sample "Aé中🐟Z")
(check (string-length sample) => 5)
(check (string->list sample) => (list #\A #\é #\中 #\🐟 #\Z))
(check (list->string (string->list sample)) => sample)
(check (string-ref sample 1) => #\é)
(check (string-ref sample 2) => #\中)
(check (string-ref sample 3) => #\🐟)
(check (substring sample 1 4) => "é中🐟")
(check (string-copy sample 2) => "中🐟Z")
(check (string-copy sample 5) => "")
(check (string-copy sample 2 2) => "")
(check (bytevector-length (string->utf8 sample)) => 11)
(check (utf8->string (string->utf8 sample 1 4)) => "é中🐟")
(check (string->utf8 sample 5) => #u8())
(check (string-length "e\x301;") => 2)
(check (string-ref "\x0;中" 0) => #\null)
(check (make-string 3 #\🐟) => "🐟🐟🐟")
(check (string #\é #\中 #\🐟) => "é中🐟")

;; Replacing a character can change byte width without changing length.
(let ((s (string-copy sample)))
  (string-set! s 0 #\🐟)
  (check s => "🐟é中🐟Z")
  (string-set! s 3 #\a)
  (check s => "🐟é中aZ")
  (string-set! s 1 #\null)
  (check s => "🐟\x0;中aZ")
  (check (string-length s) => 5)
  (check sample => "Aé中🐟Z"))
(let ((s (string-copy sample)))
  (string-fill! s #\é 1 4)
  (check s => "AéééZ")
  (string-fill! s #\🐟 4)
  (check s => "Aééé🐟")
  (string-fill! s #\a)
  (check s => "aaaaa"))
(let ((s (string-copy "-----")))
  (string-copy! s 1 sample 1 4)
  (check s => "-é中🐟-")
  (string-copy! s 0 sample 3)
  (check s => "🐟Z中🐟-")
  (string-copy! s 5 "")
  (check (string-length s) => 5))
(let ((s (string-copy sample)))
  (string-copy! s 1 s 0 4)
  (check s => "AAé中🐟"))
(let ((s (string-copy sample)))
  (string-copy! s 0 s 1 5)
  (check s => "é中🐟ZZ"))

;; Traversal operates on complete characters and stops at the shortest input.
(check (string-map (lambda (c) c) sample) => sample)
(check (string-map (lambda (a b) b) "é中" "A🐟Z") => "A🐟")
(let ((seen '()))
  (string-for-each (lambda (c) (set! seen (cons c seen))) sample)
  (check (reverse seen) => (string->list sample)))
(let ((seen '()))
  (string-for-each (lambda (a b) (set! seen (cons (list a b) seen))) "é中" "A🐟Z")
  (check (reverse seen) => (list (list #\é #\A) (list #\中 #\🐟))))

;; Text ports advance by characters, while binary I/O retains raw bytes.
(let ((p (open-input-string sample)))
  (check (peek-char p) => #\A)
  (check (peek-char p) => #\A)
  (check (read-string 2 p) => "Aé")
  (check (peek-char p) => #\中)
  (check (read-char p) => #\中)
  (check (read-string 10 p) => "🐟Z")
  (check (eof-object? (read-char p)) => #t)
  (check (eof-object? (peek-char p)) => #t)
  (check (eof-object? (read-string 1 p)) => #t)
  (check (read-string 0 p) => ""))
(let ((p (open-input-string "é中\n🐟Z")))
  (check (read-line p) => "é中")
  (check (read-string 1 p) => "🐟")
  (check (read-line p) => "Z"))
(call-with-input-file "tests/resources/unicode-text.txt"
  (lambda (p)
    (check (read-string 3 p) => "Aé中")
    (check (read-line p) => "🐟Z")
    (check (eof-object? (read-char p)) => #t)))
(let ((p (open-output-string)))
  (write-string sample p 1 4)
  (write-char #\é p)
  (write-string sample p 4)
  (check (get-output-string p) => "é中🐟éZ"))
(let ((p (open-input-bytevector #u8(0 127 128 255))))
  (check (peek-u8 p) => 0)
  (check (read-u8 p) => 0)
  (check (read-bytevector 3 p) => #u8(127 128 255))
  (check (eof-object? (read-u8 p)) => #t))
(let ((p (open-output-bytevector)))
  (write-u8 255 p)
  (write-bytevector #u8(0 127 128 255) p)
  (check (get-output-bytevector p) => #u8(255 0 127 128 255)))

;; The source reader must not decode already decoded port characters again.
(let ((p (open-input-string "#\\é #\\中 #\\🐟")))
  (check (read p) => #\é)
  (check (read p) => #\中)
  (check (read p) => #\🐟))
(check (read (open-input-string "\"é中🐟\"")) => "é中🐟")
(check (read (open-input-string "中文")) => (string->symbol "中文"))

(check-catch 'out-of-range (string-ref sample 5))
(check-catch 'out-of-range (substring sample 1 6))
(check-catch 'out-of-range (string-set! (string-copy sample) 5 #\a))
(check-catch 'out-of-range (string-copy! (string-copy sample) 4 "é中"))
(check-report)
