(import (scheme base) (scheme write) (scheme char))
(define (sum-to n)
  (let loop ((i 0) (s 0))
    (if (> i n) s (loop (+ i 1) (+ s i)))))
(define (fib n)
  (if (< n 2) n (+ (fib (- n 1)) (fib (- n 2)))))
(define words (map symbol->string '(alpha beta gamma)))
(define upcased (map (lambda (s) (list->string (map char-upcase (string->list s)))) words))
(write (list (sum-to 1000) (fib 18) upcased))
(newline)
