(import (liii json) (scheme base) (scheme time))

(define (build-object-json count)
  (let ((out (open-output-string)))
    (display "{" out)
    (do ((i 0 (+ i 1)))
      ((= i count))
      (when (> i 0) (display "," out))
      (display "\"k" out)
      (display i out)
      (display "\":" out)
      (display i out))
    (display "}" out)
    (get-output-string out)))

(define object-value (string->json (build-object-json 200)))

;; Single-pass candidate for json-keys: validate the alist as keys are copied.
(define (json-keys-one-pass json)
  (if (not (list? json))
      '()
      (let loop ((rest json) (keys '()))
        (cond ((null? rest) (reverse keys))
              ((not (pair? (car rest))) '())
              (else (loop (cdr rest) (cons (caar rest) keys)))))))

(define (require-result condition message)
  (unless condition (error "JSON benchmark result check failed" message)))

(define (time-keys label procedure count)
  (let ((start (monotonic-nanosecond)))
    (do ((i 0 (+ i 1))) ((= i count)) (procedure object-value))
    (let ((elapsed (- (monotonic-nanosecond) start)))
      (display "JSON-KEYS-AB ")
      (display label)
      (display " count=")
      (display count)
      (display " ns=")
      (display elapsed)
      (newline))))

(let ((expected (json-keys object-value)))
  (require-result (equal? expected (json-keys-one-pass object-value))
                  "valid object keys")
  (require-result (equal? (json-keys '(())) (json-keys-one-pass '(())))
                  "empty object keys")
  (require-result (equal? (json-keys '(bad)) (json-keys-one-pass '(bad)))
                  "malformed object result")
  (require-result (equal? (json-keys '( (a . 1) . bad))
                          (json-keys-one-pass '( (a . 1) . bad)))
                  "improper object result")
  (do ((i 0 (+ i 1))) ((= i 100))
    (json-keys object-value)
    (json-keys-one-pass object-value))
  (time-keys "existing-1" json-keys 4000)
  (time-keys "candidate-1" json-keys-one-pass 4000)
  (time-keys "candidate-2" json-keys-one-pass 4000)
  (time-keys "existing-2" json-keys 4000)
  (time-keys "existing-3" json-keys 4000)
  (time-keys "candidate-3" json-keys-one-pass 4000))
(display "JSON-KEYS-AB-OK\n")
