(import (liii json) (scheme base) (scheme time))

(define (build-object-json count)
  (let ((out (open-output-string)))
    (display "{" out)
    (do ((i 0 (+ i 1)))
      ((= i count))
      (when (> i 0) (display "," out))
      (display "\"k" out)
      (display i out)
      (display "\":" out)
      (display i out))
    (display "}" out)
    (get-output-string out)))

(define object-json (build-object-json 200))
(define object-value (string->json object-json))
(define target-key "k150")
(define (require-result condition message)
  (unless condition (error "JSON benchmark result check failed" message)))
(define (time-phase label count thunk)
  (display "PHASE-BEGIN\t") (display label) (newline)
  (flush-output-port (current-output-port))
  (let ((start (monotonic-nanosecond)))
    (do ((i 0 (+ i 1))) ((= i count)) (thunk))
    (let ((elapsed (- (monotonic-nanosecond) start)))
      (display "PHASE\t") (display label) (display "\t") (display elapsed) (newline)
      (flush-output-port (current-output-port))
      (display "JSON-PHASE ") (display label)
      (display " count=") (display count)
      (display " ns=") (display elapsed) (newline) elapsed)))
(define (warm-up thunk)
  (do ((i 0 (+ i 1))) ((= i 10)) (thunk)))

(warm-up (lambda () (string->json object-json)))
(time-phase "parse" 80 (lambda () (string->json object-json)))
(let ((parsed (string->json object-json)))
  (require-result (= (length (json-keys parsed)) 200) "object key count")
  (require-result (= (json-ref parsed target-key) 150) "parsed target value"))
(display "JSON-PHASE-OK parse\n")
