#!/bin/sh
set -eu
cd "$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
verify=no
record=no
case "${1:-}" in
  '') ;;
  --verify-recorded) verify=yes ;;
  --record) record=yes ;;
  *) echo "usage: sh tools/test-r7rs-semantics.sh [--verify-recorded|--record]" >&2; exit 2 ;;
esac
if [ "$record" = yes ]; then
    sh tools/check-r7rs-semantics.sh --ledger-only
else
    sh tools/check-r7rs-semantics.sh
fi
xmake build gf-native
result_root=$(mktemp -d "${TMPDIR:-/tmp}/goldfish-r7rs-semantics.XXXXXX")
export GOLDFISH_CACHE_DIR="$result_root/ccache"
files=$(sed '/^[[:space:]]*#/d; /^[[:space:]]*$/d; /\/list-cycle.scm$/d' tests/r7rs/semantic-audit.manifest)
{
  git rev-parse HEAD
  ./bin/gf --bootstrap-cache-directory
  sha256sum bin/gf tests/r7rs/fixtures/standard-exports.scm
  sha256sum tests/r7rs/audit/*.scm tests/r7rs/fixtures/semantic-audit.scm
} > "$result_root/runtime.txt"
for phase in cold warm; do
    echo "R7RS semantics: $phase; logs at $result_root"
    code=0
    # Standard assertions remain failing for the recorded gaps.
    # shellcheck disable=SC2086
    timeout 600s ./bin/gf -m liii --each-file $files > "$result_root/$phase.log" 2>&1 || code=$?
    case "$code" in 0|1) ;; *) cat "$result_root/$phase.log"; exit "$code" ;; esac
    cycle_code=0
    timeout 60s ./bin/gf -m liii tests/r7rs/audit/list-cycle.scm \
        > "$result_root/$phase-cycle.log" 2>&1 || cycle_code=$?
    case "$cycle_code" in
      0|1|255) ;;
      124)
        rg -q '^;;;AUDIT-START data.list-cycle$' "$result_root/$phase-cycle.log"
        if rg -q '^;;;AUDIT data.list-cycle ' "$result_root/$phase-cycle.log"; then
            echo "cycle probe timed out after producing a result" >&2; exit 1
        fi
        printf ';;;AUDIT data.list-cycle gap\n;;;RESULT data.list-cycle (timeout 60s-after-start)\n' >> "$result_root/$phase-cycle.log" ;;
      *) cat "$result_root/$phase-cycle.log"; exit "$cycle_code" ;;
    esac
    awk '$1 == ";;;AUDIT" && NF == 3 {print $2 "\t" $3}' \
        "$result_root/$phase.log" "$result_root/$phase-cycle.log" | sort > "$result_root/$phase.tsv"
    awk '$1 == ";;;RESULT" {line=$0; sub(/^;;;RESULT [^ ]+ /,"",line); print $2 "\t" line}' \
        "$result_root/$phase.log" "$result_root/$phase-cycle.log" | sort > "$result_root/$phase-observations.tsv"
    awk -F '\t' '!/^#/ && $1 != "id" {print $1}' R7RS-SEMANTIC-AUDIT.tsv | sort > "$result_root/expected-ids"
    cut -f1 "$result_root/$phase.tsv" > "$result_root/actual-ids"
    diff -u "$result_root/expected-ids" "$result_root/actual-ids"
    cut -f1 "$result_root/$phase-observations.tsv" > "$result_root/observation-ids"
    diff -u "$result_root/expected-ids" "$result_root/observation-ids"
    awk -F '\t' '{n[$2]++} END {printf "  %d pass, %d gap\n", n["pass"], n["gap"]}' "$result_root/$phase.tsv"
done
diff -u "$result_root/cold.tsv" "$result_root/warm.tsv"
diff -u "$result_root/cold-observations.tsv" "$result_root/warm-observations.tsv"
tab=$(printf '\t')
join -t "$tab" "$result_root/cold.tsv" "$result_root/warm.tsv" > "$result_root/statuses.tsv"
{
    printf '# Native runtime sources at %s; recorded %s.\n' "$(git rev-parse --short HEAD)" "$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
    printf '# Generated by sh tools/test-r7rs-semantics.sh --record; not a conformance certificate.\n'
    printf '# Native executable SHA256: %s\n' "$(sha256sum bin/gf | cut -d ' ' -f1)"
    printf '# Export reference SHA256: %s\n' "$(sha256sum tests/r7rs/fixtures/standard-exports.scm | cut -d ' ' -f1)"
    printf 'id\tcold\twarm\tobservation\n'
    join -t "$tab" "$result_root/statuses.tsv" "$result_root/warm-observations.tsv"
} > "$result_root/results.tsv"
if [ "$record" = yes ]; then
    cp "$result_root/results.tsv" tests/r7rs/semantic-results.tsv
    sh tools/check-r7rs-semantics.sh
fi
if [ "$verify" = yes ]; then
    awk -F '\t' '!/^#/ && $1 != "id" {print $1 "\t" $3}' R7RS-SEMANTIC-AUDIT.tsv | sort > "$result_root/recorded.tsv"
    diff -u "$result_root/recorded.tsv" "$result_root/warm.tsv"
    awk -F '\t' '!/^#/ && $1 != "id" {print $1 "\t" $4}' tests/r7rs/semantic-results.tsv | sort > "$result_root/recorded-observations.tsv"
    diff -u "$result_root/recorded-observations.tsv" "$result_root/warm-observations.tsv"
    echo "R7RS semantics: recorded observations reproduced; this is not a conformance pass"
else
    if rg -q '\tgap$' "$result_root/warm.tsv"; then exit 1; fi
fi
