(import (liii check)
        (liii go))
(check-set-mode! 'report-failed)
(define meta-ch (make-chan 2))
(define sub-ch (make-chan 2))
(chan-send! sub-ch "secret")
(chan-send! meta-ch sub-ch)
(define received-sub-ch (chan-recv! meta-ch))
(check (chan? received-sub-ch) => #t)
(check (chan-recv! received-sub-ch) => "secret")
(check-report)
