(import (liii check)
        (liii go))
(check-set-mode! 'report-failed)
(define ch (make-chan 5))
(chan-send! ch 100)
(chan-close! ch)
(check (chan-recv! ch) => 100)
(check (eof-object? (chan-recv! ch)) => #t)
(check (eof-object? (chan-try-recv! ch)) => #t)
(chan-close! ch)
(check (chan-closed? ch) => #t)
(check-report)
