(import (goldfish) (scheme base))
(display (let* ((x 1)) (cond ((= x 1) (case 1 ((1) (and #t #t)))) (else #f)))) (newline)
(display (when #t (do ((i 0 (+ i 1))) ((= i 2) (force (delay 42)))))) (newline)
(display (+ 1 2)) (newline)
(display (let ((a 1) (b 2)) (if (and (> a 0) (or #t (> b 3))) (parameterize () 9) 0))) (newline)
(display (let-values (((x y) (values 1 2))) (+ x y))) (newline)
(display (guard (e (#t 42)) (raise 1))) (newline)
(display (define-record-type pt (make-pt x) pt? (x pt-x))) (newline)
(display (catch #t (lambda () (syntax-error "boom")) (lambda args 'syntax-error-raised))) (newline)
