(import (liii check) (liii string) (goldfish))

;; Native ABI regression: the driver loads native-abi.scm before libraries.

(check (min 3 1 2) => 1)
(check (max 3 1 2) => 3)
(check (exact-integer? 5) => #t)
(check (finite? 1) => #t)
(check (string-upcase "abc") => "ABC")
(check (string-downcase "AbC") => "abc")
(check (char-upcase #\a) => #\A)
(check (char-ci=? #\a #\A) => #t)
(check (string-ci=? "abc" "ABC") => #t)
(check (bytevector-copy! (make-bytevector 3) 0 (bytevector 1 2 3)) => (bytevector 1 2 3))
(check (promise? (make-promise 5)) => #t)
(check (force (make-promise 5)) => 5)
(check (truncate-quotient 7 2) => 3)
(check (truncate-remainder 7 2) => 1)
(check (eof-object? (read-u8 (open-input-bytevector (bytevector 1 2)))) => #f)
(check (get-output-bytevector (begin (write-u8 65 (open-output-bytevector)) (open-output-bytevector))) => (bytevector))
(check-report)
