;;; Conditional expansion shares one requirement evaluator and clause selector.
(define *cond-expand-features* '(r7rs goldfish))

(define (cond-expand-requirement-valid? req)
  (let ((d (syntax->datum req)))
    (cond
      ((symbol? d) #t)
      ((and (list? d) (pair? d))
       (case (car d)
         ((and or) (let loop ((rs (cdr d)))
                     (or (null? rs)
                         (and (cond-expand-requirement-valid? (car rs)) (loop (cdr rs))))))
         ((not) (and (= (length d) 2) (cond-expand-requirement-valid? (cadr d))))
         ((library)
          (and (= (length d) 2)
               ((module-ref the-expander-library 'library-name-valid?) (cadr d))))
         (else #f)))
      (else #f))))

(define (cond-expand-feature-satisfied? req)
  (let ((d (syntax->datum req)))
    (unless (cond-expand-requirement-valid? d)
      (error 'cond-expand "invalid feature requirement" d))
    (cond
      ((symbol? d) (if (memq d *cond-expand-features*) #t #f))
      ((eq? (car d) 'and)
       (let loop ((rs (cdr d)))
         (or (null? rs) (and (cond-expand-feature-satisfied? (car rs)) (loop (cdr rs))))))
      ((eq? (car d) 'or)
       (let loop ((rs (cdr d)))
         (and (pair? rs) (or (cond-expand-feature-satisfied? (car rs)) (loop (cdr rs))))))
      ((eq? (car d) 'not) (not (cond-expand-feature-satisfied? (cadr d))))
      (else ((module-ref the-expander-library 'library-available?) (cadr d))))))

(define (cond-expand-select clauses)
  (let validate ((rest clauses))
    (unless (null? rest)
      (let ((clause (syntax->datum (car rest))))
        (unless (and (list? clause) (pair? clause))
          (error 'cond-expand "invalid clause" clause))
        (if (eq? (car clause) 'else)
          (unless (null? (cdr rest)) (error 'cond-expand "else must be last" clause))
          (unless (cond-expand-requirement-valid? (car clause))
            (error 'cond-expand "invalid feature requirement" (car clause))))
      (validate (cdr rest)))))
  (let select ((rest clauses))
    (if (null? rest)
      '()
      (let* ((clause (car rest))
             (form (if (syntax? clause) (syntax-form clause) clause)))
        (if (or (eq? (syntax->datum (car form)) 'else)
                (cond-expand-feature-satisfied? (car form)))
          (cdr form)
          (select (cdr rest)))))))

(define-syntax cond-expand
  (lambda (stx)
    (datum->syntax stx (cons 'begin (cond-expand-select (cdr (syntax-form stx)))))))
